# Generated by Django 5.2.14 on 2026-05-21 13:42

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='giftnotification',
            new_name='gifts_giftn_recipie_cd4043_idx',
            old_name='gifts_giftn_recipie_idx',
        ),
        migrations.AlterField(
            model_name='giftnotification',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='giftnotification',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
