# Generated by Django 5.2.14 on 2026-05-20 20:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pokedex_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('type_1', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], max_length=16)),
                ('type_2', models.CharField(blank=True, choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], default='', max_length=16)),
                ('base_hp', models.PositiveSmallIntegerField()),
                ('base_attack', models.PositiveSmallIntegerField()),
                ('base_defense', models.PositiveSmallIntegerField()),
                ('base_sp_attack', models.PositiveSmallIntegerField()),
                ('base_sp_defense', models.PositiveSmallIntegerField()),
                ('base_speed', models.PositiveSmallIntegerField()),
                ('sprite_url', models.URLField(blank=True, default='', max_length=512)),
                ('official_artwork_url', models.URLField(blank=True, default='', max_length=512)),
                ('evolution_chain_url', models.URLField(blank=True, default='', max_length=512)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16)),
                ('workout_pools', models.JSONField(blank=True, default=dict, help_text='Workout pool configuration keyed by activity or muscle group.')),
            ],
            options={
                'verbose_name': 'Pokémon species',
                'verbose_name_plural': 'Pokémon species',
                'ordering': ('pokedex_id',),
            },
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('experience', models.PositiveIntegerField(default=0)),
                ('nature', models.CharField(choices=[('hardy', 'Hardy'), ('lonely', 'Lonely'), ('brave', 'Brave'), ('adamant', 'Adamant'), ('naughty', 'Naughty'), ('bold', 'Bold'), ('docile', 'Docile'), ('relaxed', 'Relaxed'), ('impish', 'Impish'), ('lax', 'Lax'), ('timid', 'Timid'), ('hasty', 'Hasty'), ('serious', 'Serious'), ('jolly', 'Jolly'), ('naive', 'Naive'), ('modest', 'Modest'), ('mild', 'Mild'), ('quiet', 'Quiet'), ('bashful', 'Bashful'), ('rash', 'Rash'), ('calm', 'Calm'), ('gentle', 'Gentle'), ('sassy', 'Sassy'), ('careful', 'Careful'), ('quirky', 'Quirky')], default='hardy', max_length=16)),
                ('shiny', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField()),
                ('active_team_slot', models.PositiveSmallIntegerField(blank=True, help_text='Team position 1-6 when assigned to the active roster.', null=True)),
                ('affection', models.PositiveIntegerField(default=0)),
                ('source_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_pokemon', to='workouts.workout')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon', to='pokemon.pokemonspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user Pokémon',
                'verbose_name_plural': 'user Pokémon',
                'ordering': ('-captured_at',),
            },
        ),
        migrations.CreateModel(
            name='PokemonIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('attack', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('defense', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('sp_attack', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('sp_defense', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('speed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('user_pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ivs', to='pokemon.userpokemon')),
            ],
            options={
                'verbose_name': 'Pokémon IV',
                'verbose_name_plural': 'Pokémon IVs',
            },
        ),
        migrations.CreateModel(
            name='PokemonEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hp', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('attack', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('defense', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('sp_attack', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('sp_defense', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('speed', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('total', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('user_pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evs', to='pokemon.userpokemon')),
            ],
            options={
                'verbose_name': 'Pokémon EV',
                'verbose_name_plural': 'Pokémon EVs',
            },
        ),
        migrations.AddConstraint(
            model_name='userpokemon',
            constraint=models.CheckConstraint(condition=models.Q(('active_team_slot__isnull', True), models.Q(('active_team_slot__gte', 1), ('active_team_slot__lte', 6)), _connector='OR'), name='user_pokemon_active_team_slot_range'),
        ),
        migrations.AddConstraint(
            model_name='userpokemon',
            constraint=models.UniqueConstraint(condition=models.Q(('active_team_slot__isnull', False)), fields=('user', 'active_team_slot'), name='user_pokemon_unique_active_team_slot'),
        ),
    ]
