"""
Popula o catálogo de exercícios.

1. Edite a lista EXERCISES abaixo neste arquivo.
2. Rode:

     poetry run python manage.py seed_exercises
     poetry run python manage.py seed_exercises --dry-run
     poetry run python manage.py seed_exercises --create-only

Campos por exercício
--------------------
name            (obrigatório) Nome no catálogo
slug            (opcional)    Identificador estável; se omitido, gera do name
description     (opcional)    Resumo curto (até 255 caracteres)
instructions    (opcional)    Passo a passo / dicas
muscle_group    (obrigatório) chest | back | legs | shoulders | arms | core | cardio | full_body | mobility
difficulty      (obrigatório) beginner | intermediate | advanced
equipment       (opcional)    Ex: "Barra", "Halteres", "Peso corporal"
video_url       (opcional)    URL do vídeo
image_path      (opcional)    Caminho local da imagem (relativo ao cwd do backend ou absoluto)
is_active       (opcional)    True (padrão) ou False para ocultar do catálogo
"""

from django.core.management.base import BaseCommand, CommandError

from workouts.services.seed_exercises import SeedStatus, ingest_exercises_list

# ——— Edite sua lista aqui ———
EXERCISES: list[dict] = [
    {
        "name": "Supino reto com halteres",
        "slug": "supino-reto-com-halteres",
        "description": "Exercício de peito feito em banco reto com halteres.",
        "instructions": "Deite no banco, mantenha os pés firmes no chão, desça os halteres de forma controlada até a linha do peito e empurre para cima sem travar totalmente os cotovelos.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Halteres, banco reto",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Supino reto com barra",
        "slug": "supino-reto-com-barra",
        "description": "Exercício clássico para desenvolvimento do peitoral.",
        "instructions": "Deite no banco, segure a barra com pegada média, desça até próximo ao peito e empurre para cima mantendo o controle.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Barra, anilhas, banco reto",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Supino inclinado com halteres",
        "slug": "supino-inclinado-com-halteres",
        "description": "Variação do supino com foco na parte superior do peito.",
        "instructions": "Ajuste o banco inclinado, segure os halteres acima do peito, desça com controle e empurre para cima mantendo os ombros estáveis.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Halteres, banco inclinado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Supino inclinado com barra",
        "slug": "supino-inclinado-com-barra",
        "description": "Exercício para peitoral superior usando barra.",
        "instructions": "Deite no banco inclinado, segure a barra com pegada média, desça até a parte superior do peito e empurre com controle.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Barra, anilhas, banco inclinado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Supino declinado com barra",
        "slug": "supino-declinado-com-barra",
        "description": "Variação do supino com foco na parte inferior do peitoral.",
        "instructions": "Deite no banco declinado, fixe bem os pés, desça a barra até a região inferior do peito e empurre para cima.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Barra, anilhas, banco declinado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Crucifixo reto com halteres",
        "slug": "crucifixo-reto-com-halteres",
        "description": "Exercício de isolamento para o peitoral.",
        "instructions": "Deite no banco, mantenha os halteres acima do peito, abra os braços com leve flexão nos cotovelos e retorne contraindo o peitoral.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Halteres, banco reto",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Crucifixo inclinado com halteres",
        "slug": "crucifixo-inclinado-com-halteres",
        "description": "Isolamento para a parte superior do peitoral.",
        "instructions": "Deite no banco inclinado, abra os braços de forma controlada e una os halteres acima do peito sem bater os pesos.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Halteres, banco inclinado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Crossover na polia",
        "slug": "crossover-na-polia",
        "description": "Exercício de peitoral feito na polia com cabos.",
        "instructions": "Fique entre as polias, segure os puxadores, incline levemente o tronco e una as mãos à frente do corpo contraindo o peitoral.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Polia, puxadores",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Flexão de braço",
        "slug": "flexao-de-braco",
        "description": "Exercício com peso corporal para peito, tríceps e ombros.",
        "instructions": "Apoie as mãos no chão, mantenha o corpo alinhado, desça até próximo ao chão e empurre o corpo para cima.",
        "muscle_group": "chest",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Flexão inclinada",
        "slug": "flexao-inclinada",
        "description": "Variação mais fácil da flexão tradicional.",
        "instructions": "Apoie as mãos em um banco ou superfície elevada, mantenha o corpo alinhado, desça com controle e empurre para cima.",
        "muscle_group": "chest",
        "difficulty": "beginner",
        "equipment": "Banco ou apoio elevado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Flexão declinada",
        "slug": "flexao-declinada",
        "description": "Variação da flexão com maior foco no peitoral superior.",
        "instructions": "Apoie os pés em uma superfície elevada, mantenha o corpo alinhado, desça até próximo ao chão e suba com controle.",
        "muscle_group": "chest",
        "difficulty": "intermediate",
        "equipment": "Banco ou apoio elevado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Peck deck",
        "slug": "peck-deck",
        "description": "Exercício de isolamento para o peitoral na máquina.",
        "instructions": "Sente na máquina, apoie os braços nas almofadas, una os cotovelos à frente do corpo e volte devagar.",
        "muscle_group": "chest",
        "difficulty": "beginner",
        "equipment": "Máquina peck deck",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Puxada frontal",
        "slug": "puxada-frontal",
        "description": "Exercício para costas com foco no latíssimo do dorso.",
        "instructions": "Sente na máquina, segure a barra acima da cabeça, puxe até a parte superior do peito e retorne com controle.",
        "muscle_group": "back",
        "difficulty": "beginner",
        "equipment": "Máquina de puxada, barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Puxada aberta",
        "slug": "puxada-aberta",
        "description": "Variação de puxada com pegada aberta para as costas.",
        "instructions": "Segure a barra com pegada aberta, puxe em direção ao peito mantendo o tronco estável e retorne devagar.",
        "muscle_group": "back",
        "difficulty": "beginner",
        "equipment": "Máquina de puxada, barra aberta",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Puxada neutra",
        "slug": "puxada-neutra",
        "description": "Puxada para costas usando pegada neutra.",
        "instructions": "Segure o puxador neutro, puxe em direção ao peito, contraia as costas e retorne controlando o peso.",
        "muscle_group": "back",
        "difficulty": "beginner",
        "equipment": "Máquina de puxada, puxador neutro",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Remada curvada com barra",
        "slug": "remada-curvada-com-barra",
        "description": "Exercício composto para espessura das costas.",
        "instructions": "Incline o tronco, mantenha a coluna neutra, puxe a barra em direção ao abdômen e desça com controle.",
        "muscle_group": "back",
        "difficulty": "intermediate",
        "equipment": "Barra, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Remada unilateral com halter",
        "slug": "remada-unilateral-com-halter",
        "description": "Remada para costas feita com um braço por vez.",
        "instructions": "Apoie uma mão e um joelho no banco, puxe o halter em direção ao quadril e desça controlando o movimento.",
        "muscle_group": "back",
        "difficulty": "intermediate",
        "equipment": "Halter, banco",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Remada baixa",
        "slug": "remada-baixa",
        "description": "Exercício de costas feito sentado na polia baixa.",
        "instructions": "Sente com a coluna ereta, segure o puxador, puxe em direção ao abdômen e retorne sem arredondar as costas.",
        "muscle_group": "back",
        "difficulty": "beginner",
        "equipment": "Polia baixa, puxador",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Remada cavalinho",
        "slug": "remada-cavalinho",
        "description": "Remada pesada para costas e dorsais.",
        "instructions": "Posicione-se na máquina ou com barra apoiada, mantenha o tronco firme, puxe a carga em direção ao abdômen e desça controlando.",
        "muscle_group": "back",
        "difficulty": "intermediate",
        "equipment": "Máquina cavalinho ou barra, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Barra fixa",
        "slug": "barra-fixa",
        "description": "Exercício com peso corporal para costas e braços.",
        "instructions": "Segure a barra, mantenha o corpo firme, puxe até o queixo passar da barra e desça com controle.",
        "muscle_group": "back",
        "difficulty": "advanced",
        "equipment": "Barra fixa",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Pulldown com braços retos",
        "slug": "pulldown-com-bracos-retos",
        "description": "Isolamento para dorsais usando polia.",
        "instructions": "Segure a barra na polia alta, mantenha os braços quase estendidos e puxe a barra até a linha da coxa.",
        "muscle_group": "back",
        "difficulty": "intermediate",
        "equipment": "Polia alta, barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Face pull",
        "slug": "face-pull",
        "description": "Exercício para parte alta das costas e ombros posteriores.",
        "instructions": "Segure a corda na polia alta, puxe em direção ao rosto abrindo os cotovelos e retorne devagar.",
        "muscle_group": "back",
        "difficulty": "beginner",
        "equipment": "Polia, corda",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Levantamento terra",
        "slug": "levantamento-terra",
        "description": "Exercício composto para costas, pernas e cadeia posterior.",
        "instructions": "Com a barra no chão, posicione os pés na largura do quadril, mantenha a coluna neutra, levante a barra estendendo quadril e joelhos e retorne controlando.",
        "muscle_group": "back",
        "difficulty": "advanced",
        "equipment": "Barra, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Hiperextensão lombar",
        "slug": "hiperextensao-lombar",
        "description": "Exercício para lombar e cadeia posterior.",
        "instructions": "Apoie o corpo no banco romano, desça o tronco com controle e suba até alinhar o corpo sem hiperestender a lombar.",
        "muscle_group": "back",
        "difficulty": "beginner",
        "equipment": "Banco romano",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Agachamento livre",
        "slug": "agachamento-livre",
        "description": "Exercício composto para pernas e glúteos.",
        "instructions": "Posicione a barra nas costas, mantenha os pés firmes, desça flexionando joelhos e quadril e suba empurrando o chão.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Barra, rack, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Agachamento goblet",
        "slug": "agachamento-goblet",
        "description": "Agachamento segurando um peso à frente do corpo.",
        "instructions": "Segure um halter ou kettlebell junto ao peito, desça mantendo o tronco firme e suba empurrando o chão.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Halter ou kettlebell",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Agachamento frontal",
        "slug": "agachamento-frontal",
        "description": "Variação do agachamento com maior demanda de quadríceps e core.",
        "instructions": "Apoie a barra à frente dos ombros, mantenha o tronco ereto, desça com controle e suba mantendo os cotovelos altos.",
        "muscle_group": "legs",
        "difficulty": "advanced",
        "equipment": "Barra, rack, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Leg press",
        "slug": "leg-press",
        "description": "Exercício de pernas feito na máquina.",
        "instructions": "Apoie os pés na plataforma, destrave a máquina, desça flexionando os joelhos e empurre sem travar totalmente as pernas.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Máquina leg press",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Cadeira extensora",
        "slug": "cadeira-extensora",
        "description": "Exercício de isolamento para quadríceps.",
        "instructions": "Sente na máquina, ajuste o apoio nos tornozelos, estenda os joelhos até o topo e retorne devagar.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Máquina extensora",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Mesa flexora",
        "slug": "mesa-flexora",
        "description": "Exercício de isolamento para posteriores de coxa.",
        "instructions": "Deite na máquina, ajuste o apoio nos tornozelos, flexione os joelhos trazendo o peso em direção aos glúteos e retorne com controle.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Mesa flexora",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Cadeira flexora",
        "slug": "cadeira-flexora",
        "description": "Exercício sentado para posteriores de coxa.",
        "instructions": "Sente na máquina, ajuste os apoios, flexione os joelhos puxando a carga para baixo e retorne devagar.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Cadeira flexora",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Stiff com barra",
        "slug": "stiff-com-barra",
        "description": "Exercício para posteriores de coxa e glúteos.",
        "instructions": "Segure a barra à frente do corpo, incline o tronco levando o quadril para trás, mantenha a coluna neutra e retorne contraindo glúteos.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Barra, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Stiff com halteres",
        "slug": "stiff-com-halteres",
        "description": "Variação do stiff usando halteres.",
        "instructions": "Segure os halteres à frente das coxas, leve o quadril para trás, desça mantendo a coluna neutra e suba contraindo glúteos.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Afundo com halteres",
        "slug": "afundo-com-halteres",
        "description": "Exercício unilateral para pernas e glúteos.",
        "instructions": "Segure os halteres ao lado do corpo, dê um passo à frente, desça até os joelhos formarem ângulos próximos de 90 graus e suba.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Passada caminhando",
        "slug": "passada-caminhando",
        "description": "Exercício dinâmico para pernas e glúteos.",
        "instructions": "Dê passos longos à frente, desça o corpo controlando o joelho da frente e avance alternando as pernas.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Peso corporal ou halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Agachamento búlgaro",
        "slug": "agachamento-bulgaro",
        "description": "Exercício unilateral intenso para pernas e glúteos.",
        "instructions": "Apoie o pé de trás em um banco, mantenha o pé da frente firme, desça com controle e suba empurrando o chão.",
        "muscle_group": "legs",
        "difficulty": "advanced",
        "equipment": "Banco, halteres opcionais",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Panturrilha em pé",
        "slug": "panturrilha-em-pe",
        "description": "Exercício para panturrilhas feito em pé.",
        "instructions": "Apoie a ponta dos pés, eleve os calcanhares o máximo possível e desça controlando o movimento.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Máquina ou peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Panturrilha sentado",
        "slug": "panturrilha-sentado",
        "description": "Exercício para panturrilhas com foco no sóleo.",
        "instructions": "Sente na máquina, apoie a ponta dos pés, eleve os calcanhares e retorne com controle.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Máquina de panturrilha sentado",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Elevação pélvica",
        "slug": "elevacao-pelvica",
        "description": "Exercício para glúteos e posteriores.",
        "instructions": "Apoie as costas no banco, posicione a carga sobre o quadril, eleve o quadril contraindo os glúteos e desça com controle.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Banco, barra ou máquina",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Abdução de quadril",
        "slug": "abducao-de-quadril",
        "description": "Exercício para glúteos médios e estabilidade do quadril.",
        "instructions": "Sente na máquina, apoie as pernas nas almofadas, abra os joelhos contra a resistência e retorne devagar.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Máquina abdutora",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Adução de quadril",
        "slug": "aducao-de-quadril",
        "description": "Exercício para parte interna das coxas.",
        "instructions": "Sente na máquina, posicione as pernas nos apoios, feche as pernas contra a resistência e retorne com controle.",
        "muscle_group": "legs",
        "difficulty": "beginner",
        "equipment": "Máquina adutora",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Step up",
        "slug": "step-up",
        "description": "Exercício unilateral para pernas e glúteos.",
        "instructions": "Suba em um banco ou caixa com uma perna, estenda o quadril e o joelho no topo e desça controlando.",
        "muscle_group": "legs",
        "difficulty": "intermediate",
        "equipment": "Banco ou caixa",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Desenvolvimento com halteres",
        "slug": "desenvolvimento-com-halteres",
        "description": "Exercício para ombros feito com halteres.",
        "instructions": "Sente ou fique em pé, segure os halteres na altura dos ombros, empurre para cima e desça com controle.",
        "muscle_group": "shoulders",
        "difficulty": "intermediate",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Desenvolvimento com barra",
        "slug": "desenvolvimento-com-barra",
        "description": "Exercício composto para ombros.",
        "instructions": "Segure a barra na frente dos ombros, empurre acima da cabeça e retorne com controle sem perder a postura.",
        "muscle_group": "shoulders",
        "difficulty": "intermediate",
        "equipment": "Barra, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Elevação lateral",
        "slug": "elevacao-lateral",
        "description": "Isolamento para a parte lateral dos ombros.",
        "instructions": "Segure os halteres ao lado do corpo, eleve os braços até a altura dos ombros e desça devagar.",
        "muscle_group": "shoulders",
        "difficulty": "beginner",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Elevação frontal",
        "slug": "elevacao-frontal",
        "description": "Exercício para a parte anterior dos ombros.",
        "instructions": "Segure halteres ou anilha à frente do corpo, eleve até a altura dos ombros e desça controlando.",
        "muscle_group": "shoulders",
        "difficulty": "beginner",
        "equipment": "Halteres ou anilha",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Crucifixo inverso",
        "slug": "crucifixo-inverso",
        "description": "Exercício para ombros posteriores e parte alta das costas.",
        "instructions": "Incline o tronco, segure os halteres abaixo do corpo, abra os braços para os lados e retorne com controle.",
        "muscle_group": "shoulders",
        "difficulty": "intermediate",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Remada alta",
        "slug": "remada-alta",
        "description": "Exercício para ombros e trapézio.",
        "instructions": "Segure a barra ou halteres à frente do corpo, puxe em direção ao peito mantendo os cotovelos altos e desça devagar.",
        "muscle_group": "shoulders",
        "difficulty": "intermediate",
        "equipment": "Barra ou halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Arnold press",
        "slug": "arnold-press",
        "description": "Variação de desenvolvimento para ombros.",
        "instructions": "Comece com os halteres à frente do rosto, gire os braços enquanto empurra para cima e retorne pelo mesmo caminho.",
        "muscle_group": "shoulders",
        "difficulty": "intermediate",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Encolhimento com halteres",
        "slug": "encolhimento-com-halteres",
        "description": "Exercício para trapézio.",
        "instructions": "Segure os halteres ao lado do corpo, eleve os ombros em direção às orelhas e desça com controle.",
        "muscle_group": "shoulders",
        "difficulty": "beginner",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Elevação lateral na polia",
        "slug": "elevacao-lateral-na-polia",
        "description": "Isolamento para deltoide lateral usando polia.",
        "instructions": "Segure o puxador da polia baixa, eleve o braço lateralmente até a altura do ombro e retorne devagar.",
        "muscle_group": "shoulders",
        "difficulty": "intermediate",
        "equipment": "Polia baixa, puxador",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Desenvolvimento na máquina",
        "slug": "desenvolvimento-na-maquina",
        "description": "Exercício guiado para ombros.",
        "instructions": "Sente na máquina, ajuste o banco, empurre os pegadores para cima e retorne com controle.",
        "muscle_group": "shoulders",
        "difficulty": "beginner",
        "equipment": "Máquina de desenvolvimento",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Rosca direta com barra",
        "slug": "rosca-direta-com-barra",
        "description": "Exercício básico para bíceps.",
        "instructions": "Segure a barra com as palmas para cima, flexione os cotovelos levando a barra em direção ao peito e desça controlando.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Rosca alternada",
        "slug": "rosca-alternada",
        "description": "Exercício para bíceps feito com halteres.",
        "instructions": "Segure um halter em cada mão, flexione um braço por vez, contraia o bíceps no topo e desça controlando.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Rosca martelo",
        "slug": "rosca-martelo",
        "description": "Exercício para bíceps e braquial.",
        "instructions": "Segure os halteres com pegada neutra, flexione os cotovelos mantendo os punhos alinhados e desça com controle.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Rosca concentrada",
        "slug": "rosca-concentrada",
        "description": "Exercício de isolamento para bíceps.",
        "instructions": "Sente no banco, apoie o cotovelo na parte interna da coxa, flexione o braço e desça devagar.",
        "muscle_group": "arms",
        "difficulty": "intermediate",
        "equipment": "Halter",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Rosca Scott",
        "slug": "rosca-scott",
        "description": "Exercício de bíceps feito no banco Scott.",
        "instructions": "Apoie os braços no banco, segure a barra, flexione os cotovelos e desça controlando sem estender totalmente.",
        "muscle_group": "arms",
        "difficulty": "intermediate",
        "equipment": "Banco Scott, barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Rosca na polia",
        "slug": "rosca-na-polia",
        "description": "Exercício de bíceps usando polia baixa.",
        "instructions": "Segure a barra da polia baixa, mantenha os cotovelos próximos ao corpo, flexione os braços e retorne devagar.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Polia baixa, barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Tríceps corda",
        "slug": "triceps-corda",
        "description": "Exercício para tríceps na polia.",
        "instructions": "Segure a corda na polia alta, mantenha os cotovelos fixos, estenda os braços para baixo e abra a corda no final.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Polia alta, corda",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Tríceps barra na polia",
        "slug": "triceps-barra-na-polia",
        "description": "Exercício para tríceps usando barra na polia.",
        "instructions": "Segure a barra na polia alta, mantenha os cotovelos junto ao corpo, estenda os braços e retorne com controle.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Polia alta, barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Tríceps francês",
        "slug": "triceps-frances",
        "description": "Exercício de tríceps acima da cabeça.",
        "instructions": "Segure um halter ou barra acima da cabeça, flexione os cotovelos levando o peso para trás e estenda novamente.",
        "muscle_group": "arms",
        "difficulty": "intermediate",
        "equipment": "Halter ou barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Tríceps testa",
        "slug": "triceps-testa",
        "description": "Exercício para tríceps feito deitado.",
        "instructions": "Deite no banco, segure a barra acima do peito, flexione os cotovelos levando a barra em direção à testa e estenda novamente.",
        "muscle_group": "arms",
        "difficulty": "intermediate",
        "equipment": "Barra, banco",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Mergulho no banco",
        "slug": "mergulho-no-banco",
        "description": "Exercício com peso corporal para tríceps.",
        "instructions": "Apoie as mãos no banco, mantenha os pés à frente, desça flexionando os cotovelos e suba estendendo os braços.",
        "muscle_group": "arms",
        "difficulty": "beginner",
        "equipment": "Banco",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Paralelas",
        "slug": "paralelas",
        "description": "Exercício composto para tríceps, peito e ombros.",
        "instructions": "Apoie-se nas barras paralelas, desça flexionando os cotovelos e suba estendendo os braços com controle.",
        "muscle_group": "arms",
        "difficulty": "advanced",
        "equipment": "Barras paralelas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Rosca inversa",
        "slug": "rosca-inversa",
        "description": "Exercício para antebraços e braquial.",
        "instructions": "Segure a barra com as palmas para baixo, flexione os cotovelos e retorne controlando a descida.",
        "muscle_group": "arms",
        "difficulty": "intermediate",
        "equipment": "Barra",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Prancha",
        "slug": "prancha",
        "description": "Exercício isométrico para core.",
        "instructions": "Apoie os antebraços e a ponta dos pés no chão, mantenha o corpo alinhado e sustente a posição.",
        "muscle_group": "core",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Prancha lateral",
        "slug": "prancha-lateral",
        "description": "Exercício isométrico para oblíquos e estabilidade do core.",
        "instructions": "Apoie um antebraço no chão, alinhe o corpo de lado, eleve o quadril e mantenha a posição.",
        "muscle_group": "core",
        "difficulty": "intermediate",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Abdominal crunch",
        "slug": "abdominal-crunch",
        "description": "Exercício básico para abdômen.",
        "instructions": "Deite no chão, flexione os joelhos, eleve levemente o tronco contraindo o abdômen e retorne devagar.",
        "muscle_group": "core",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Abdominal infra",
        "slug": "abdominal-infra",
        "description": "Exercício para a região inferior do abdômen.",
        "instructions": "Deite no chão, mantenha as pernas elevadas, levante o quadril levemente e retorne com controle.",
        "muscle_group": "core",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Elevação de pernas",
        "slug": "elevacao-de-pernas",
        "description": "Exercício para abdômen e flexores do quadril.",
        "instructions": "Deite ou fique suspenso, eleve as pernas mantendo o controle e desça sem relaxar totalmente o abdômen.",
        "muscle_group": "core",
        "difficulty": "intermediate",
        "equipment": "Peso corporal ou barra fixa",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Abdominal bicicleta",
        "slug": "abdominal-bicicleta",
        "description": "Exercício dinâmico para abdômen e oblíquos.",
        "instructions": "Deite no chão, alterne cotovelo em direção ao joelho oposto enquanto estende a outra perna.",
        "muscle_group": "core",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Russian twist",
        "slug": "russian-twist",
        "description": "Exercício para oblíquos e rotação do tronco.",
        "instructions": "Sente no chão, incline levemente o tronco para trás, gire o corpo de um lado para o outro com controle.",
        "muscle_group": "core",
        "difficulty": "intermediate",
        "equipment": "Peso corporal, anilha ou medicine ball",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Mountain climber",
        "slug": "mountain-climber",
        "description": "Exercício dinâmico para core e condicionamento.",
        "instructions": "Fique em posição de flexão, leve os joelhos alternadamente em direção ao peito mantendo o abdômen contraído.",
        "muscle_group": "core",
        "difficulty": "intermediate",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Dead bug",
        "slug": "dead-bug",
        "description": "Exercício de estabilidade para core.",
        "instructions": "Deite de barriga para cima, eleve braços e pernas, estenda braço e perna opostos e retorne alternando os lados.",
        "muscle_group": "core",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Ab wheel",
        "slug": "ab-wheel",
        "description": "Exercício avançado para core usando roda abdominal.",
        "instructions": "Ajoelhe no chão, segure a roda, role para frente mantendo o abdômen firme e volte sem perder o controle.",
        "muscle_group": "core",
        "difficulty": "advanced",
        "equipment": "Roda abdominal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Esteira caminhada",
        "slug": "esteira-caminhada",
        "description": "Cardio leve feito na esteira.",
        "instructions": "Caminhe em ritmo confortável, mantenha postura ereta e ajuste velocidade e inclinação conforme o objetivo.",
        "muscle_group": "cardio",
        "difficulty": "beginner",
        "equipment": "Esteira",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Esteira corrida",
        "slug": "esteira-corrida",
        "description": "Cardio moderado ou intenso feito na esteira.",
        "instructions": "Corra mantendo postura estável, respiração controlada e velocidade adequada ao seu nível.",
        "muscle_group": "cardio",
        "difficulty": "intermediate",
        "equipment": "Esteira",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Bicicleta ergométrica",
        "slug": "bicicleta-ergometrica",
        "description": "Cardio de baixo impacto feito na bicicleta.",
        "instructions": "Ajuste o banco, pedale em ritmo constante e controle a resistência conforme o objetivo do treino.",
        "muscle_group": "cardio",
        "difficulty": "beginner",
        "equipment": "Bicicleta ergométrica",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Elíptico",
        "slug": "eliptico",
        "description": "Cardio de baixo impacto para corpo inteiro.",
        "instructions": "Suba no aparelho, mantenha o tronco ereto, movimente braços e pernas em ritmo constante.",
        "muscle_group": "cardio",
        "difficulty": "beginner",
        "equipment": "Elíptico",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Remo ergométrico",
        "slug": "remo-ergometrico",
        "description": "Cardio com grande participação de pernas, costas e braços.",
        "instructions": "Empurre com as pernas, puxe o cabo em direção ao abdômen, retorne primeiro os braços e depois flexione as pernas.",
        "muscle_group": "cardio",
        "difficulty": "intermediate",
        "equipment": "Remo ergométrico",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Pular corda",
        "slug": "pular-corda",
        "description": "Cardio intenso com coordenação e resistência.",
        "instructions": "Segure a corda, mantenha saltos baixos e constantes, gire os punhos e mantenha ritmo controlado.",
        "muscle_group": "cardio",
        "difficulty": "intermediate",
        "equipment": "Corda",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Burpee",
        "slug": "burpee",
        "description": "Exercício de corpo inteiro para condicionamento.",
        "instructions": "Agache, apoie as mãos no chão, estenda as pernas para trás, retorne ao agachamento e salte.",
        "muscle_group": "full_body",
        "difficulty": "advanced",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Polichinelo",
        "slug": "polichinelo",
        "description": "Exercício simples para aquecimento e cardio.",
        "instructions": "Salte abrindo pernas e braços ao mesmo tempo, depois retorne à posição inicial em ritmo contínuo.",
        "muscle_group": "cardio",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Corrida estacionária",
        "slug": "corrida-estacionaria",
        "description": "Cardio feito sem deslocamento.",
        "instructions": "Corra parado elevando os joelhos de forma alternada e mantendo o ritmo constante.",
        "muscle_group": "cardio",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Kettlebell swing",
        "slug": "kettlebell-swing",
        "description": "Exercício explosivo para glúteos, posteriores e condicionamento.",
        "instructions": "Segure o kettlebell, leve o quadril para trás, projete o peso para frente com extensão do quadril e controle a volta.",
        "muscle_group": "full_body",
        "difficulty": "intermediate",
        "equipment": "Kettlebell",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Thruster com halteres",
        "slug": "thruster-com-halteres",
        "description": "Movimento completo combinando agachamento e desenvolvimento.",
        "instructions": "Segure os halteres nos ombros, faça um agachamento e ao subir empurre os halteres acima da cabeça.",
        "muscle_group": "full_body",
        "difficulty": "advanced",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Clean com barra",
        "slug": "clean-com-barra",
        "description": "Movimento olímpico para potência de corpo inteiro.",
        "instructions": "Com a barra no chão, levante de forma explosiva, puxe o corpo para baixo da barra e receba-a nos ombros.",
        "muscle_group": "full_body",
        "difficulty": "advanced",
        "equipment": "Barra, anilhas",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Snatch com halter",
        "slug": "snatch-com-halter",
        "description": "Movimento explosivo unilateral para corpo inteiro.",
        "instructions": "Com o halter entre as pernas, estenda quadril e joelhos de forma explosiva e leve o peso acima da cabeça em um movimento contínuo.",
        "muscle_group": "full_body",
        "difficulty": "advanced",
        "equipment": "Halter",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Farmer walk",
        "slug": "farmer-walk",
        "description": "Exercício de pegada, core e condicionamento.",
        "instructions": "Segure pesos pesados ao lado do corpo, mantenha a postura ereta e caminhe por uma distância definida.",
        "muscle_group": "full_body",
        "difficulty": "intermediate",
        "equipment": "Halteres ou kettlebells",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Wall ball",
        "slug": "wall-ball",
        "description": "Exercício de corpo inteiro com agachamento e arremesso.",
        "instructions": "Segure a bola no peito, agache, suba arremessando a bola contra a parede e receba-a para repetir.",
        "muscle_group": "full_body",
        "difficulty": "intermediate",
        "equipment": "Medicine ball",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Man maker",
        "slug": "man-maker",
        "description": "Exercício complexo de corpo inteiro com halteres.",
        "instructions": "Com halteres no chão, faça flexão, remada, leve os pesos aos ombros e finalize com agachamento e desenvolvimento.",
        "muscle_group": "full_body",
        "difficulty": "advanced",
        "equipment": "Halteres",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Bear crawl",
        "slug": "bear-crawl",
        "description": "Exercício de locomoção para core, ombros e condicionamento.",
        "instructions": "Apoie mãos e pés no chão, mantenha os joelhos próximos ao solo e avance alternando mãos e pés.",
        "muscle_group": "full_body",
        "difficulty": "intermediate",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },

    {
        "name": "Alongamento de peitoral na parede",
        "slug": "alongamento-de-peitoral-na-parede",
        "description": "Mobilidade e alongamento para peitoral e ombros.",
        "instructions": "Apoie o braço na parede, gire o tronco levemente para o lado oposto e mantenha a posição sem dor.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Parede",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Alongamento de posterior de coxa",
        "slug": "alongamento-de-posterior-de-coxa",
        "description": "Alongamento para posteriores de coxa.",
        "instructions": "Com uma perna estendida, incline o tronco à frente mantendo a coluna neutra até sentir alongar a parte de trás da coxa.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Alongamento de quadríceps em pé",
        "slug": "alongamento-de-quadriceps-em-pe",
        "description": "Alongamento para a parte anterior da coxa.",
        "instructions": "Em pé, segure o tornozelo, leve o calcanhar em direção ao glúteo e mantenha os joelhos próximos.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Mobilidade de tornozelo",
        "slug": "mobilidade-de-tornozelo",
        "description": "Exercício para melhorar a mobilidade do tornozelo.",
        "instructions": "Com o pé apoiado no chão, leve o joelho à frente sem tirar o calcanhar do solo e retorne.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal ou parede",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Mobilidade torácica em quatro apoios",
        "slug": "mobilidade-toracica-em-quatro-apoios",
        "description": "Exercício para mobilidade da coluna torácica.",
        "instructions": "Em quatro apoios, leve uma mão atrás da cabeça, gire o tronco abrindo o cotovelo e retorne com controle.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Cat cow",
        "slug": "cat-cow",
        "description": "Movimento de mobilidade para coluna.",
        "instructions": "Em quatro apoios, alterne entre arquear e arredondar a coluna de forma lenta e controlada.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "World's greatest stretch",
        "slug": "worlds-greatest-stretch",
        "description": "Alongamento dinâmico para quadril, posterior e coluna.",
        "instructions": "Dê um passo à frente em posição de avanço, apoie as mãos no chão, gire o tronco para o lado da perna da frente e alterne.",
        "muscle_group": "mobility",
        "difficulty": "intermediate",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Child's pose",
        "slug": "childs-pose",
        "description": "Alongamento relaxante para coluna, quadril e ombros.",
        "instructions": "Ajoelhe no chão, sente sobre os calcanhares, estenda os braços à frente e relaxe o tronco.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Pombo",
        "slug": "pombo",
        "description": "Alongamento para glúteos e quadril.",
        "instructions": "Leve uma perna flexionada à frente do corpo, estenda a outra para trás e incline o tronco conforme a mobilidade permitir.",
        "muscle_group": "mobility",
        "difficulty": "intermediate",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
    {
        "name": "Alongamento de flexor do quadril",
        "slug": "alongamento-de-flexor-do-quadril",
        "description": "Alongamento para a região anterior do quadril.",
        "instructions": "Fique em posição de meio ajoelhado, projete o quadril levemente para frente e mantenha o tronco ereto.",
        "muscle_group": "mobility",
        "difficulty": "beginner",
        "equipment": "Peso corporal",
        "video_url": "",
        "image_path": "",
        "is_active": True,
    },
]


class Command(BaseCommand):
    help = "Popula o catálogo de exercícios a partir da lista EXERCISES neste arquivo."

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Valida e simula sem gravar no banco.",
        )
        parser.add_argument(
            "--create-only",
            action="store_true",
            help="Não atualiza exercícios já existentes (match por slug ou name).",
        )

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        update_existing = not options["create_only"]

        if dry_run:
            self.stdout.write(self.style.WARNING("Modo dry-run — nada será salvo."))

        if not EXERCISES:
            raise CommandError("Lista EXERCISES vazia — adicione exercícios no comando.")

        try:
            results = ingest_exercises_list(
                EXERCISES,
                update_existing=update_existing,
                dry_run=dry_run,
            )
        except ValueError as exc:
            raise CommandError(str(exc)) from exc

        created = updated = skipped = failed = 0

        for result in results:
            if result.status == SeedStatus.CREATED:
                created += 1
                self.stdout.write(self.style.SUCCESS(f"[criado] {result.name}"))
            elif result.status == SeedStatus.UPDATED:
                updated += 1
                suffix = f" — {result.reason}" if result.reason else ""
                self.stdout.write(self.style.WARNING(f"[atualizado] {result.name}{suffix}"))
            elif result.status == SeedStatus.SKIPPED:
                skipped += 1
                self.stdout.write(self.style.NOTICE(f"[ignorado] {result.name}: {result.reason}"))
            else:
                failed += 1
                self.stdout.write(self.style.ERROR(f"[erro] {result.name}: {result.reason}"))

        self.stdout.write("")
        self.stdout.write(
            self.style.SUCCESS(
                f"Resumo: {created} criados, {updated} atualizados, "
                f"{skipped} ignorados, {failed} erros ({len(results)} itens)."
            )
        )

        if failed and not (created or updated):
            raise CommandError(f"Seed terminou com {failed} erro(s) e nenhum sucesso.")
