// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ExercisesCreateData, ExercisesCreateResponses, ExercisesDestroyData, ExercisesDestroyResponses, ExercisesListData, ExercisesListResponses, ExercisesPartialUpdateData, ExercisesPartialUpdateResponses, ExercisesRetrieveData, ExercisesRetrieveResponses, ExercisesUpdateData, ExercisesUpdateResponses, MyPokemonListData, MyPokemonListResponses, MyPokemonRandomEncounterRetrieveData, MyPokemonRandomEncounterRetrieveResponses, MyPokemonRetrieveData, MyPokemonRetrieveResponses, MyPokemonTeamListData, MyPokemonTeamListResponses, MyPokemonTeamSlotPartialUpdateData, MyPokemonTeamSlotPartialUpdateResponses, PokemonSpeciesListData, PokemonSpeciesListResponses, PokemonSpeciesRetrieveData, PokemonSpeciesRetrieveResponses, RestRestCheckRetrieveData, RestRestCheckRetrieveResponses, UsersCreateData, UsersCreateResponses, UsersDestroyData, UsersDestroyResponses, UsersListData, UsersListResponses, UsersLoginCreateData, UsersLoginCreateResponses, UsersLogoutCreateData, UsersLogoutCreateResponses, UsersMeRetrieveData, UsersMeRetrieveResponses, UsersPartialUpdateData, UsersPartialUpdateResponses, UsersRegisterCreateData, UsersRegisterCreateResponses, UsersRetrieveData, UsersRetrieveResponses, UsersUpdateData, UsersUpdateResponses, WorkoutsCreateData, WorkoutsCreateResponses, WorkoutsExercisesCreateData, WorkoutsExercisesCreateResponses, WorkoutsFinishCreateData, WorkoutsFinishCreateResponses, WorkoutsListData, WorkoutsListResponses, WorkoutsRetrieveData, WorkoutsRetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const exercisesList = <ThrowOnError extends boolean = false>(options?: Options<ExercisesListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ExercisesListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/exercises/',
        ...options
    });
};

export const exercisesCreate = <ThrowOnError extends boolean = false>(options: Options<ExercisesCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ExercisesCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/exercises/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const exercisesDestroy = <ThrowOnError extends boolean = false>(options: Options<ExercisesDestroyData, ThrowOnError>) => {
    return (options.client ?? client).delete<ExercisesDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/exercises/{id}/',
        ...options
    });
};

export const exercisesRetrieve = <ThrowOnError extends boolean = false>(options: Options<ExercisesRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ExercisesRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/exercises/{id}/',
        ...options
    });
};

export const exercisesPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ExercisesPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<ExercisesPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/exercises/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const exercisesUpdate = <ThrowOnError extends boolean = false>(options: Options<ExercisesUpdateData, ThrowOnError>) => {
    return (options.client ?? client).put<ExercisesUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/exercises/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const myPokemonList = <ThrowOnError extends boolean = false>(options?: Options<MyPokemonListData, ThrowOnError>) => {
    return (options?.client ?? client).get<MyPokemonListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/my-pokemon/',
        ...options
    });
};

export const myPokemonRetrieve = <ThrowOnError extends boolean = false>(options: Options<MyPokemonRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<MyPokemonRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/my-pokemon/{id}/',
        ...options
    });
};

export const myPokemonTeamSlotPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<MyPokemonTeamSlotPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<MyPokemonTeamSlotPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/my-pokemon/{id}/team-slot/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const myPokemonRandomEncounterRetrieve = <ThrowOnError extends boolean = false>(options?: Options<MyPokemonRandomEncounterRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<MyPokemonRandomEncounterRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/my-pokemon/random-encounter/',
        ...options
    });
};

export const myPokemonTeamList = <ThrowOnError extends boolean = false>(options?: Options<MyPokemonTeamListData, ThrowOnError>) => {
    return (options?.client ?? client).get<MyPokemonTeamListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/my-pokemon/team/',
        ...options
    });
};

export const pokemonSpeciesList = <ThrowOnError extends boolean = false>(options?: Options<PokemonSpeciesListData, ThrowOnError>) => {
    return (options?.client ?? client).get<PokemonSpeciesListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/pokemon-species/',
        ...options
    });
};

export const pokemonSpeciesRetrieve = <ThrowOnError extends boolean = false>(options: Options<PokemonSpeciesRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<PokemonSpeciesRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/pokemon-species/{pokedex_id}/',
        ...options
    });
};

/**
 * Check REST API
 *
 * This endpoint checks if the REST API is working.
 */
export const restRestCheckRetrieve = <ThrowOnError extends boolean = false>(options?: Options<RestRestCheckRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<RestRestCheckRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/rest/rest-check/',
        ...options
    });
};

export const usersList = <ThrowOnError extends boolean = false>(options?: Options<UsersListData, ThrowOnError>) => {
    return (options?.client ?? client).get<UsersListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options
    });
};

export const usersCreate = <ThrowOnError extends boolean = false>(options: Options<UsersCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<UsersCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const usersDestroy = <ThrowOnError extends boolean = false>(options: Options<UsersDestroyData, ThrowOnError>) => {
    return (options.client ?? client).delete<UsersDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const usersRetrieve = <ThrowOnError extends boolean = false>(options: Options<UsersRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<UsersRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const usersPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<UsersPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const usersUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersUpdateData, ThrowOnError>) => {
    return (options.client ?? client).put<UsersUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const usersLoginCreate = <ThrowOnError extends boolean = false>(options: Options<UsersLoginCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<UsersLoginCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/login/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const usersLogoutCreate = <ThrowOnError extends boolean = false>(options?: Options<UsersLogoutCreateData, ThrowOnError>) => {
    return (options?.client ?? client).post<UsersLogoutCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/logout/',
        ...options
    });
};

export const usersMeRetrieve = <ThrowOnError extends boolean = false>(options?: Options<UsersMeRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<UsersMeRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/me/',
        ...options
    });
};

export const usersRegisterCreate = <ThrowOnError extends boolean = false>(options: Options<UsersRegisterCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<UsersRegisterCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/register/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const workoutsList = <ThrowOnError extends boolean = false>(options?: Options<WorkoutsListData, ThrowOnError>) => {
    return (options?.client ?? client).get<WorkoutsListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/workouts/',
        ...options
    });
};

export const workoutsCreate = <ThrowOnError extends boolean = false>(options?: Options<WorkoutsCreateData, ThrowOnError>) => {
    return (options?.client ?? client).post<WorkoutsCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/workouts/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const workoutsRetrieve = <ThrowOnError extends boolean = false>(options: Options<WorkoutsRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<WorkoutsRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/workouts/{id}/',
        ...options
    });
};

export const workoutsExercisesCreate = <ThrowOnError extends boolean = false>(options: Options<WorkoutsExercisesCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<WorkoutsExercisesCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/workouts/{id}/exercises/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const workoutsFinishCreate = <ThrowOnError extends boolean = false>(options: Options<WorkoutsFinishCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<WorkoutsFinishCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/workouts/{id}/finish/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
