// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type BlankEnum = '';

/**
 * * `beginner` - Beginner
 * * `intermediate` - Intermediate
 * * `advanced` - Advanced
 */
export type DifficultyEnum = 'beginner' | 'intermediate' | 'advanced';

export type Exercise = {
    readonly id: number;
    name: string;
    readonly slug: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    readonly image_url: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
    readonly created_by: number | null;
    readonly created_by_email: string;
    readonly created: string;
    readonly modified: string;
};

export type ExerciseList = {
    readonly id: number;
    readonly name: string;
    readonly slug: string;
    readonly description: string;
    muscle_group: MuscleGroupEnum;
    difficulty: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    readonly equipment: string;
    readonly image_url: string | null;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    readonly is_active: boolean;
};

export type ExerciseSummary = {
    readonly id: number;
    readonly name: string;
    readonly slug: string;
    readonly description: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    readonly instructions: string;
    muscle_group: MuscleGroupEnum;
    difficulty: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    readonly equipment: string;
    readonly image_url: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    readonly video_url: string;
};

export type Message = {
    message: string;
};

/**
 * * `chest` - Chest
 * * `back` - Back
 * * `legs` - Legs
 * * `shoulders` - Shoulders
 * * `arms` - Arms
 * * `core` - Core
 * * `cardio` - Cardio
 * * `full_body` - Full body
 * * `mobility` - Mobility
 */
export type MuscleGroupEnum = 'chest' | 'back' | 'legs' | 'shoulders' | 'arms' | 'core' | 'cardio' | 'full_body' | 'mobility';

/**
 * * `hardy` - Hardy
 * * `lonely` - Lonely
 * * `brave` - Brave
 * * `adamant` - Adamant
 * * `naughty` - Naughty
 * * `bold` - Bold
 * * `docile` - Docile
 * * `relaxed` - Relaxed
 * * `impish` - Impish
 * * `lax` - Lax
 * * `timid` - Timid
 * * `hasty` - Hasty
 * * `serious` - Serious
 * * `jolly` - Jolly
 * * `naive` - Naive
 * * `modest` - Modest
 * * `mild` - Mild
 * * `quiet` - Quiet
 * * `bashful` - Bashful
 * * `rash` - Rash
 * * `calm` - Calm
 * * `gentle` - Gentle
 * * `sassy` - Sassy
 * * `careful` - Careful
 * * `quirky` - Quirky
 */
export type NatureEnum = 'hardy' | 'lonely' | 'brave' | 'adamant' | 'naughty' | 'bold' | 'docile' | 'relaxed' | 'impish' | 'lax' | 'timid' | 'hasty' | 'serious' | 'jolly' | 'naive' | 'modest' | 'mild' | 'quiet' | 'bashful' | 'rash' | 'calm' | 'gentle' | 'sassy' | 'careful' | 'quirky';

export type PaginatedExerciseListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ExerciseList>;
};

export type PaginatedPokemonSpeciesList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PokemonSpecies>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

export type PaginatedUserPokemonListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserPokemonList>;
};

export type PaginatedWorkoutListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<WorkoutList>;
};

export type PatchedExercise = {
    readonly id?: number;
    name?: string;
    readonly slug?: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    readonly image_url?: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
    readonly created_by?: number | null;
    readonly created_by_email?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedUser = {
    readonly id?: number;
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser?: boolean;
    readonly created?: string;
    readonly modified?: string;
    readonly last_login?: string | null;
};

export type PatchedUserPokemonTeamUpdate = {
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
};

export type PokemonIv = {
    hp: number;
    attack: number;
    defense: number;
    sp_attack: number;
    sp_defense: number;
    speed: number;
};

export type PokemonSpecies = {
    readonly id: number;
    pokedex_id: number;
    name: string;
    type_1: Type1Enum;
    type_2?: Type2Enum | BlankEnum;
    base_hp: number;
    base_attack: number;
    base_defense: number;
    base_sp_attack: number;
    base_sp_defense: number;
    base_speed: number;
    sprite_url?: string;
    official_artwork_url?: string;
    rarity?: RarityEnum;
    readonly image_url: string;
};

/**
 * * `common` - Common
 * * `rare` - Rare
 * * `super_rare` - Super Rare
 * * `legendary` - Legendary
 */
export type RarityEnum = 'common' | 'rare' | 'super_rare' | 'legendary';

/**
 * * `draft` - Draft
 * * `finished` - Finished
 * * `cancelled` - Cancelled
 */
export type StatusEnum = 'draft' | 'finished' | 'cancelled';

/**
 * * `normal` - Normal
 * * `fire` - Fire
 * * `water` - Water
 * * `electric` - Electric
 * * `grass` - Grass
 * * `ice` - Ice
 * * `fighting` - Fighting
 * * `poison` - Poison
 * * `ground` - Ground
 * * `flying` - Flying
 * * `psychic` - Psychic
 * * `bug` - Bug
 * * `rock` - Rock
 * * `ghost` - Ghost
 * * `dragon` - Dragon
 * * `dark` - Dark
 * * `steel` - Steel
 * * `fairy` - Fairy
 */
export type Type1Enum = 'normal' | 'fire' | 'water' | 'electric' | 'grass' | 'ice' | 'fighting' | 'poison' | 'ground' | 'flying' | 'psychic' | 'bug' | 'rock' | 'ghost' | 'dragon' | 'dark' | 'steel' | 'fairy';

/**
 * * `normal` - Normal
 * * `fire` - Fire
 * * `water` - Water
 * * `electric` - Electric
 * * `grass` - Grass
 * * `ice` - Ice
 * * `fighting` - Fighting
 * * `poison` - Poison
 * * `ground` - Ground
 * * `flying` - Flying
 * * `psychic` - Psychic
 * * `bug` - Bug
 * * `rock` - Rock
 * * `ghost` - Ghost
 * * `dragon` - Dragon
 * * `dark` - Dark
 * * `steel` - Steel
 * * `fairy` - Fairy
 */
export type Type2Enum = 'normal' | 'fire' | 'water' | 'electric' | 'grass' | 'ice' | 'fighting' | 'poison' | 'ground' | 'flying' | 'psychic' | 'bug' | 'rock' | 'ghost' | 'dragon' | 'dark' | 'steel' | 'fairy';

export type User = {
    readonly id: number;
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser: boolean;
    readonly created: string;
    readonly modified: string;
    readonly last_login: string | null;
};

export type UserPokemonDetail = {
    readonly id: number;
    species: PokemonSpecies;
    nickname?: string;
    readonly display_name: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
    ivs: PokemonIv;
    readonly created: string;
    readonly modified: string;
};

export type UserPokemonList = {
    readonly id: number;
    species: PokemonSpecies;
    nickname?: string;
    readonly display_name: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
};

export type UserPokemonTeamUpdate = {
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
};

/**
 * * `manual` - Manual
 * * `health_app` - Health app
 * * `location` - Location
 * * `wearable_location` - Wearable + location
 */
export type ValidationTypeEnum = 'manual' | 'health_app' | 'location' | 'wearable_location';

export type WorkoutCreate = {
    readonly id: number;
    workout_type?: WorkoutTypeEnum;
    started_at?: string;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    perceived_effort?: number | null;
    validation_type?: ValidationTypeEnum;
    status: StatusEnum;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutDetail = {
    readonly id: number;
    workout_type: WorkoutTypeEnum;
    readonly started_at: string;
    readonly ended_at: string | null;
    readonly duration_minutes: number | null;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    readonly perceived_effort: number | null;
    validation_type: ValidationTypeEnum;
    readonly quality_score: number;
    readonly progress_score: number;
    status: StatusEnum;
    readonly exercises: Array<WorkoutExercise>;
    readonly total_volume: string;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutExercise = {
    readonly id: number;
    exercise: ExerciseSummary;
    /**
     * Snapshot of the catalog name at the time of the workout.
     */
    readonly name: string;
    sets: number;
    reps: number;
    weight?: string;
    readonly volume: string;
    is_pr?: boolean;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutExerciseCreate = {
    readonly id: number;
    exercise: number;
    sets: number;
    reps: number;
    weight?: string;
    is_pr?: boolean;
    readonly volume: string;
    /**
     * Snapshot of the catalog name at the time of the workout.
     */
    readonly name: string;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutFinish = {
    perceived_effort?: number | null;
};

export type WorkoutList = {
    readonly id: number;
    workout_type: WorkoutTypeEnum;
    readonly started_at: string;
    readonly ended_at: string | null;
    readonly duration_minutes: number | null;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    readonly perceived_effort: number | null;
    validation_type: ValidationTypeEnum;
    readonly quality_score: number;
    readonly progress_score: number;
    status: StatusEnum;
    readonly exercise_count: number;
    readonly total_volume: string;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `chest_triceps` - Chest & triceps
 * * `back_biceps` - Back & biceps
 * * `legs` - Legs
 * * `shoulders` - Shoulders
 * * `arms` - Arms
 * * `cardio` - Cardio
 * * `full_body` - Full body
 * * `mobility` - Mobility
 */
export type WorkoutTypeEnum = 'chest_triceps' | 'back_biceps' | 'legs' | 'shoulders' | 'arms' | 'cardio' | 'full_body' | 'mobility';

export type ExerciseWritable = {
    name: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
};

export type PaginatedExerciseListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedWorkoutListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PatchedExerciseWritable = {
    name?: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
};

export type PatchedUserWritable = {
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
};

export type PokemonSpeciesWritable = {
    pokedex_id: number;
    name: string;
    type_1: Type1Enum;
    type_2?: Type2Enum | BlankEnum;
    base_hp: number;
    base_attack: number;
    base_defense: number;
    base_sp_attack: number;
    base_sp_defense: number;
    base_speed: number;
    sprite_url?: string;
    official_artwork_url?: string;
    rarity?: RarityEnum;
};

export type UserWritable = {
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
};

export type UserPokemonDetailWritable = {
    nickname?: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
};

export type UserPokemonListWritable = {
    nickname?: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
};

export type WorkoutCreateWritable = {
    workout_type?: WorkoutTypeEnum;
    started_at?: string;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    perceived_effort?: number | null;
    validation_type?: ValidationTypeEnum;
};

export type WorkoutDetailWritable = {
    [key: string]: unknown;
};

export type WorkoutExerciseWritable = {
    sets: number;
    reps: number;
    weight?: string;
    is_pr?: boolean;
};

export type WorkoutExerciseCreateWritable = {
    exercise: number;
    sets: number;
    reps: number;
    weight?: string;
    is_pr?: boolean;
};

export type ExercisesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/exercises/';
};

export type ExercisesListResponses = {
    200: PaginatedExerciseListList;
};

export type ExercisesListResponse = ExercisesListResponses[keyof ExercisesListResponses];

export type ExercisesCreateData = {
    body: ExerciseWritable;
    path?: never;
    query?: never;
    url: '/api/exercises/';
};

export type ExercisesCreateResponses = {
    201: Exercise;
};

export type ExercisesCreateResponse = ExercisesCreateResponses[keyof ExercisesCreateResponses];

export type ExercisesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ExercisesDestroyResponse = ExercisesDestroyResponses[keyof ExercisesDestroyResponses];

export type ExercisesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesRetrieveResponses = {
    200: Exercise;
};

export type ExercisesRetrieveResponse = ExercisesRetrieveResponses[keyof ExercisesRetrieveResponses];

export type ExercisesPartialUpdateData = {
    body?: PatchedExerciseWritable;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesPartialUpdateResponses = {
    200: Exercise;
};

export type ExercisesPartialUpdateResponse = ExercisesPartialUpdateResponses[keyof ExercisesPartialUpdateResponses];

export type ExercisesUpdateData = {
    body: ExerciseWritable;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesUpdateResponses = {
    200: Exercise;
};

export type ExercisesUpdateResponse = ExercisesUpdateResponses[keyof ExercisesUpdateResponses];

export type MyPokemonListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/my-pokemon/';
};

export type MyPokemonListResponses = {
    200: PaginatedUserPokemonListList;
};

export type MyPokemonListResponse = MyPokemonListResponses[keyof MyPokemonListResponses];

export type MyPokemonRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/my-pokemon/{id}/';
};

export type MyPokemonRetrieveResponses = {
    200: UserPokemonDetail;
};

export type MyPokemonRetrieveResponse = MyPokemonRetrieveResponses[keyof MyPokemonRetrieveResponses];

export type MyPokemonTeamSlotPartialUpdateData = {
    body?: PatchedUserPokemonTeamUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/my-pokemon/{id}/team-slot/';
};

export type MyPokemonTeamSlotPartialUpdateResponses = {
    200: UserPokemonTeamUpdate;
};

export type MyPokemonTeamSlotPartialUpdateResponse = MyPokemonTeamSlotPartialUpdateResponses[keyof MyPokemonTeamSlotPartialUpdateResponses];

export type MyPokemonRandomEncounterRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/my-pokemon/random-encounter/';
};

export type MyPokemonRandomEncounterRetrieveResponses = {
    200: PokemonSpecies;
};

export type MyPokemonRandomEncounterRetrieveResponse = MyPokemonRandomEncounterRetrieveResponses[keyof MyPokemonRandomEncounterRetrieveResponses];

export type MyPokemonTeamListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/my-pokemon/team/';
};

export type MyPokemonTeamListResponses = {
    200: PaginatedUserPokemonListList;
};

export type MyPokemonTeamListResponse = MyPokemonTeamListResponses[keyof MyPokemonTeamListResponses];

export type PokemonSpeciesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/pokemon-species/';
};

export type PokemonSpeciesListResponses = {
    200: PaginatedPokemonSpeciesList;
};

export type PokemonSpeciesListResponse = PokemonSpeciesListResponses[keyof PokemonSpeciesListResponses];

export type PokemonSpeciesRetrieveData = {
    body?: never;
    path: {
        pokedex_id: number;
    };
    query?: never;
    url: '/api/pokemon-species/{pokedex_id}/';
};

export type PokemonSpeciesRetrieveResponses = {
    200: PokemonSpecies;
};

export type PokemonSpeciesRetrieveResponse = PokemonSpeciesRetrieveResponses[keyof PokemonSpeciesRetrieveResponses];

export type RestRestCheckRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rest/rest-check/';
};

export type RestRestCheckRetrieveResponses = {
    200: Message;
};

export type RestRestCheckRetrieveResponse = RestRestCheckRetrieveResponses[keyof RestRestCheckRetrieveResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/users/';
};

export type UsersListResponses = {
    200: PaginatedUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersLoginCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/login/';
};

export type UsersLoginCreateResponses = {
    200: User;
};

export type UsersLoginCreateResponse = UsersLoginCreateResponses[keyof UsersLoginCreateResponses];

export type UsersLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/logout/';
};

export type UsersLogoutCreateResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersLogoutCreateResponse = UsersLogoutCreateResponses[keyof UsersLogoutCreateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: User;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];

export type UsersRegisterCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/register/';
};

export type UsersRegisterCreateResponses = {
    200: User;
};

export type UsersRegisterCreateResponse = UsersRegisterCreateResponses[keyof UsersRegisterCreateResponses];

export type WorkoutsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/workouts/';
};

export type WorkoutsListResponses = {
    200: PaginatedWorkoutListList;
};

export type WorkoutsListResponse = WorkoutsListResponses[keyof WorkoutsListResponses];

export type WorkoutsCreateData = {
    body?: WorkoutCreateWritable;
    path?: never;
    query?: never;
    url: '/api/workouts/';
};

export type WorkoutsCreateResponses = {
    201: WorkoutCreate;
};

export type WorkoutsCreateResponse = WorkoutsCreateResponses[keyof WorkoutsCreateResponses];

export type WorkoutsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/';
};

export type WorkoutsRetrieveResponses = {
    200: WorkoutDetail;
};

export type WorkoutsRetrieveResponse = WorkoutsRetrieveResponses[keyof WorkoutsRetrieveResponses];

export type WorkoutsExercisesCreateData = {
    body: WorkoutExerciseCreateWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/exercises/';
};

export type WorkoutsExercisesCreateResponses = {
    200: WorkoutExerciseCreate;
};

export type WorkoutsExercisesCreateResponse = WorkoutsExercisesCreateResponses[keyof WorkoutsExercisesCreateResponses];

export type WorkoutsFinishCreateData = {
    body?: WorkoutFinish;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/finish/';
};

export type WorkoutsFinishCreateResponses = {
    200: WorkoutFinish;
};

export type WorkoutsFinishCreateResponse = WorkoutsFinishCreateResponses[keyof WorkoutsFinishCreateResponses];
