// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type BlankEnum = '';

export type CardioPreview = {
    duration_minutes: number;
    pace_minutes: number;
    pace_seconds: number;
};

export type CardioReference = {
    reference_pace_seconds_per_km: number;
    reference_pace_display: string;
    has_previous_cardio: boolean;
    last_cardio_ended_at: string | null;
    last_cardio_duration_minutes: number | null;
    last_cardio_pace_display: string | null;
};

export type CardioSession = {
    duration_minutes: number;
    pace_minutes: number;
    pace_seconds: number;
};

export type CardioWorkoutFinish = {
    duration_minutes?: number;
    pace_minutes?: number;
    pace_seconds?: number;
    perceived_effort?: number | null;
};

/**
 * * `beginner` - Beginner
 * * `intermediate` - Intermediate
 * * `advanced` - Advanced
 */
export type DifficultyEnum = 'beginner' | 'intermediate' | 'advanced';

/**
 * * `pending` - Pending
 * * `captured` - Captured
 * * `fled` - Fled
 */
export type EncounterStatusEnum = 'pending' | 'captured' | 'fled';

export type EvolutionPreview = {
    species_name: string;
    pokedex_id: number;
    trigger: string;
    requires_level?: number | null;
    requires_affection?: number | null;
};

export type Exercise = {
    readonly id: number;
    name: string;
    readonly slug: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    readonly image_url: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
    readonly created_by: number | null;
    readonly created_by_email: string;
    readonly created: string;
    readonly modified: string;
};

export type ExerciseList = {
    readonly id: number;
    readonly name: string;
    readonly slug: string;
    readonly description: string;
    muscle_group: MuscleGroupEnum;
    difficulty: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    readonly equipment: string;
    readonly image_url: string | null;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    readonly is_active: boolean;
};

export type ExerciseSummary = {
    readonly id: number;
    readonly name: string;
    readonly slug: string;
    readonly description: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    readonly instructions: string;
    muscle_group: MuscleGroupEnum;
    difficulty: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    readonly equipment: string;
    readonly image_url: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    readonly video_url: string;
};

/**
 * E-mail ou nickname: use `identifier` ou o campo legado `email`.
 */
export type FriendRequestCreate = {
    email?: string;
    identifier?: string;
};

export type FriendRequestsResponse = {
    incoming: Array<Friendship>;
    outgoing: Array<Friendship>;
};

export type Friendship = {
    readonly id: number;
    from_user: UserBrief;
    to_user: UserBrief;
    status: FriendshipStatusEnum;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `pending` - Pending
 * * `accepted` - Accepted
 * * `declined` - Declined
 * * `blocked` - Blocked
 */
export type FriendshipStatusEnum = 'pending' | 'accepted' | 'declined' | 'blocked';

export type GiftClaim = {
    species_id?: number | null;
};

/**
 * * `direct` - Presente direto
 * * `choice` - Escolher um Pokémon
 */
export type GiftKindEnum = 'direct' | 'choice';

export type GiftNotification = {
    readonly id: number;
    readonly batch_id: string;
    readonly message: string;
    gift_kind: GiftKindEnum;
    status: GiftNotificationStatusEnum;
    readonly is_pending: string;
    readonly sender_display: string;
    readonly species_options: Array<GiftSpeciesOption>;
    readonly claimed_at: string | null;
    readonly created: string;
};

/**
 * * `pending` - Pendente
 * * `claimed` - Resgatado
 */
export type GiftNotificationStatusEnum = 'pending' | 'claimed';

export type GiftSend = {
    recipient_ids: Array<number>;
    message: string;
    gift_kind: GiftKindEnum;
    species_ids: Array<number>;
};

export type GiftSendResult = {
    sent_count: number;
    batch_id: string;
    notifications: Array<GiftNotification>;
};

export type GiftSpeciesOption = {
    readonly id: number;
    species: PokemonSpecies;
    sort_order?: number;
};

export type LastWorkoutByType = {
    readonly id: number;
    workout_type: WorkoutTypeEnum;
    readonly ended_at: string | null;
    readonly duration_minutes: number | null;
    readonly total_volume: string;
    /**
     * Duration of the cardio session in minutes.
     */
    readonly cardio_duration_minutes: number | null;
    /**
     * Average pace in seconds per kilometer (lower is faster).
     */
    readonly cardio_pace_seconds_per_km: number | null;
    readonly cardio_pace_display: string;
    readonly exercises: Array<WorkoutExercise>;
};

export type Login = {
    email: string;
    password: string;
};

export type Message = {
    message: string;
};

/**
 * * `chest` - Chest
 * * `back` - Back
 * * `legs` - Legs
 * * `shoulders` - Shoulders
 * * `arms` - Arms
 * * `core` - Core
 * * `cardio` - Cardio
 * * `full_body` - Full body
 * * `mobility` - Mobility
 */
export type MuscleGroupEnum = 'chest' | 'back' | 'legs' | 'shoulders' | 'arms' | 'core' | 'cardio' | 'full_body' | 'mobility';

/**
 * * `hardy` - Hardy
 * * `lonely` - Lonely
 * * `brave` - Brave
 * * `adamant` - Adamant
 * * `naughty` - Naughty
 * * `bold` - Bold
 * * `docile` - Docile
 * * `relaxed` - Relaxed
 * * `impish` - Impish
 * * `lax` - Lax
 * * `timid` - Timid
 * * `hasty` - Hasty
 * * `serious` - Serious
 * * `jolly` - Jolly
 * * `naive` - Naive
 * * `modest` - Modest
 * * `mild` - Mild
 * * `quiet` - Quiet
 * * `bashful` - Bashful
 * * `rash` - Rash
 * * `calm` - Calm
 * * `gentle` - Gentle
 * * `sassy` - Sassy
 * * `careful` - Careful
 * * `quirky` - Quirky
 */
export type NatureEnum = 'hardy' | 'lonely' | 'brave' | 'adamant' | 'naughty' | 'bold' | 'docile' | 'relaxed' | 'impish' | 'lax' | 'timid' | 'hasty' | 'serious' | 'jolly' | 'naive' | 'modest' | 'mild' | 'quiet' | 'bashful' | 'rash' | 'calm' | 'gentle' | 'sassy' | 'careful' | 'quirky';

export type PaginatedExerciseListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ExerciseList>;
};

export type PaginatedPokemonSpeciesList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PokemonSpecies>;
};

export type PaginatedUserBriefList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserBrief>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

export type PaginatedUserPokemonListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserPokemonList>;
};

export type PaginatedWorkoutListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<WorkoutList>;
};

export type PatchedCardioSession = {
    duration_minutes?: number;
    pace_minutes?: number;
    pace_seconds?: number;
};

export type PatchedExercise = {
    readonly id?: number;
    name?: string;
    readonly slug?: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    readonly image_url?: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
    readonly created_by?: number | null;
    readonly created_by_email?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedUser = {
    readonly id?: number;
    email?: string;
    /**
     * Apelido único visível no app (3–24 caracteres, a-z, 0-9, _).
     */
    nickname?: string;
    readonly display_name?: string;
    /**
     * Slug do sprite de treinador (Pokémon Showdown).
     */
    trainer_sprite?: string;
    readonly trainer_sprite_url?: string;
    /**
     * Código pessoal de convite. Quem se cadastrar com este código vira amigo e dá um presente ao dono.
     */
    readonly invite_code?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser?: boolean;
    readonly created?: string;
    readonly modified?: string;
    readonly last_login?: string | null;
};

export type PatchedUserPokemonTeamUpdate = {
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
};

export type PatchedWorkoutDetail = {
    readonly id?: number;
    workout_type?: WorkoutTypeEnum;
    readonly started_at?: string;
    readonly ended_at?: string | null;
    readonly duration_minutes?: number | null;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    readonly perceived_effort?: number | null;
    validation_type?: ValidationTypeEnum;
    readonly quality_score?: number;
    readonly progress_score?: number;
    status?: Status31eEnum;
    encounter_status?: EncounterStatusEnum;
    encounter_species?: PokemonSpecies | null;
    /**
     * Level of the wild Pokémon for this encounter.
     */
    readonly encounter_level?: number | null;
    /**
     * Encontro lendário/ultra raro por bater a meta semanal neste treino.
     */
    readonly weekly_goal_reward?: boolean;
    readonly proof_photo_url?: string;
    readonly proof_caption?: string;
    readonly proof_uploaded_at?: string | null;
    /**
     * Duration of the cardio session in minutes.
     */
    readonly cardio_duration_minutes?: number | null;
    /**
     * Average pace in seconds per kilometer (lower is faster).
     */
    readonly cardio_pace_seconds_per_km?: number | null;
    readonly cardio_pace_display?: string;
    readonly exercises?: Array<WorkoutExercise>;
    readonly total_volume?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedWorkoutExerciseUpdate = {
    sets?: number;
    reps?: number;
    weight?: string;
    is_pr?: boolean;
};

export type PendingEncounter = {
    workout_id: number;
    encounter_status: string;
    encounter_level: number | null;
    weekly_goal_reward: boolean;
    readonly species: string;
};

export type PokemonIv = {
    hp: number;
    attack: number;
    defense: number;
    sp_attack: number;
    sp_defense: number;
    speed: number;
};

export type PokemonSpecies = {
    readonly id: number;
    pokedex_id: number;
    name: string;
    type_1: Type2Enum;
    type_2?: Type2Enum | BlankEnum;
    base_hp: number;
    base_attack: number;
    base_defense: number;
    base_sp_attack: number;
    base_sp_defense: number;
    base_speed: number;
    sprite_url?: string;
    official_artwork_url?: string;
    rarity?: RarityEnum;
    readonly image_url: string;
};

/**
 * * `common` - Common
 * * `rare` - Rare
 * * `super_rare` - Super Rare
 * * `legendary` - Legendary
 */
export type RarityEnum = 'common' | 'rare' | 'super_rare' | 'legendary';

export type Register = {
    email: string;
    nickname: string;
    trainer_sprite?: string;
};

export type SaveWeeklyGoal = {
    target: number;
};

/**
 * * `draft` - Draft
 * * `finished` - Finished
 * * `cancelled` - Cancelled
 */
export type Status31eEnum = 'draft' | 'finished' | 'cancelled';

export type TeamPokemonGain = {
    pokemon_id: number;
    display_name: string;
    xp_added: number;
    affection_added: number;
    level_before: number;
    level_after: number;
    evolved: boolean;
    evolved_to?: EvolutionPreview | null;
};

export type TimelineEncounter = {
    species_name: string;
    species_pokedex_id: number;
    species_sprite?: string;
    status?: string;
    captured?: boolean;
    shiny?: boolean;
};

export type TimelineEvent = {
    type: string;
    at: string;
    actor: UserBrief;
    workout?: TimelineWorkout | null;
    encounter?: TimelineEncounter | null;
    pokemon?: TimelinePokemon | null;
};

export type TimelineFeed = {
    results: Array<TimelineEvent>;
    count: number;
    next_cursor?: string | null;
};

export type TimelinePokemon = {
    id: number;
    display_name: string;
    species_name: string;
    species_pokedex_id: number;
    species_sprite?: string;
    shiny?: boolean;
};

export type TimelineWorkout = {
    id: number;
    workout_type: string;
    total_volume?: string;
    perceived_effort?: number | null;
    proof_photo_url?: string | null;
    proof_caption?: string;
    duration_minutes?: number | null;
};

/**
 * * `normal` - Normal
 * * `fire` - Fire
 * * `water` - Water
 * * `electric` - Electric
 * * `grass` - Grass
 * * `ice` - Ice
 * * `fighting` - Fighting
 * * `poison` - Poison
 * * `ground` - Ground
 * * `flying` - Flying
 * * `psychic` - Psychic
 * * `bug` - Bug
 * * `rock` - Rock
 * * `ghost` - Ghost
 * * `dragon` - Dragon
 * * `dark` - Dark
 * * `steel` - Steel
 * * `fairy` - Fairy
 */
export type Type2Enum = 'normal' | 'fire' | 'water' | 'electric' | 'grass' | 'ice' | 'fighting' | 'poison' | 'ground' | 'flying' | 'psychic' | 'bug' | 'rock' | 'ghost' | 'dragon' | 'dark' | 'steel' | 'fairy';

export type User = {
    readonly id: number;
    email: string;
    /**
     * Apelido único visível no app (3–24 caracteres, a-z, 0-9, _).
     */
    nickname: string;
    readonly display_name: string;
    /**
     * Slug do sprite de treinador (Pokémon Showdown).
     */
    trainer_sprite?: string;
    readonly trainer_sprite_url: string;
    /**
     * Código pessoal de convite. Quem se cadastrar com este código vira amigo e dá um presente ao dono.
     */
    readonly invite_code: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser: boolean;
    readonly created: string;
    readonly modified: string;
    readonly last_login: string | null;
};

export type UserBrief = {
    readonly id: number;
    readonly email: string;
    /**
     * Apelido único visível no app (3–24 caracteres, a-z, 0-9, _).
     */
    readonly nickname: string;
    readonly display_name: string;
    /**
     * Slug do sprite de treinador (Pokémon Showdown).
     */
    readonly trainer_sprite: string;
    readonly trainer_sprite_url: string;
};

export type UserPokemonCapture = {
    species_id: number;
    nickname?: string;
    shiny?: boolean;
    source_workout_id: number;
};

export type UserPokemonDetail = {
    readonly id: number;
    species: PokemonSpecies;
    nickname?: string;
    readonly display_name: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
    ivs: PokemonIv;
    readonly created: string;
    readonly modified: string;
};

export type UserPokemonList = {
    readonly id: number;
    species: PokemonSpecies;
    nickname?: string;
    readonly display_name: string;
    level?: number;
    experience?: number;
    readonly experience_to_next_level: number;
    readonly experience_progress_percent: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    readonly affection_max: number;
    readonly affection_progress_percent: number;
    readonly can_evolve: boolean;
    next_evolution: EvolutionPreview | null;
    captured_at: string;
};

export type UserPokemonTeamUpdate = {
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
};

/**
 * * `manual` - Manual
 * * `photo` - Photo proof
 * * `health_app` - Health app
 * * `location` - Location
 * * `wearable_location` - Wearable + location
 */
export type ValidationTypeEnum = 'manual' | 'photo' | 'health_app' | 'location' | 'wearable_location';

export type WeeklyGoalStatus = {
    has_active_goal: boolean;
    target: number | null;
    suggested_target: number;
    current: number;
    hp_current: number;
    hp_max: number;
    week_start: string;
    week_end: string;
    iso_year: number;
    iso_week: number;
    progress_percent: number;
    goal_met: boolean;
    reward_claimed: boolean;
    reward_workout_id: number | null;
    pending_legendary_encounter: boolean;
    goal_locked: boolean;
};

export type WorkoutCreate = {
    readonly id: number;
    workout_type?: WorkoutTypeEnum;
    started_at?: string;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    perceived_effort?: number | null;
    validation_type?: ValidationTypeEnum;
    status: Status31eEnum;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutDetail = {
    readonly id: number;
    workout_type: WorkoutTypeEnum;
    readonly started_at: string;
    readonly ended_at: string | null;
    readonly duration_minutes: number | null;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    readonly perceived_effort: number | null;
    validation_type: ValidationTypeEnum;
    readonly quality_score: number;
    readonly progress_score: number;
    status: Status31eEnum;
    encounter_status: EncounterStatusEnum;
    encounter_species: PokemonSpecies | null;
    /**
     * Level of the wild Pokémon for this encounter.
     */
    readonly encounter_level: number | null;
    /**
     * Encontro lendário/ultra raro por bater a meta semanal neste treino.
     */
    readonly weekly_goal_reward: boolean;
    readonly proof_photo_url: string;
    readonly proof_caption: string;
    readonly proof_uploaded_at: string | null;
    /**
     * Duration of the cardio session in minutes.
     */
    readonly cardio_duration_minutes: number | null;
    /**
     * Average pace in seconds per kilometer (lower is faster).
     */
    readonly cardio_pace_seconds_per_km: number | null;
    readonly cardio_pace_display: string;
    readonly exercises: Array<WorkoutExercise>;
    readonly total_volume: string;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutExercise = {
    readonly id: number;
    exercise: ExerciseSummary;
    /**
     * Snapshot of the catalog name at the time of the workout.
     */
    readonly name: string;
    sets: number;
    reps: number;
    weight?: string;
    readonly volume: string;
    is_pr?: boolean;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutExerciseBulkCreate = {
    exercises: Array<WorkoutExerciseBulkItem>;
};

export type WorkoutExerciseBulkItem = {
    exercise: number;
    sets: number;
    reps: number;
    weight: string;
};

export type WorkoutExerciseCreate = {
    readonly id: number;
    exercise: number;
    sets: number;
    reps: number;
    weight?: string;
    is_pr?: boolean;
    readonly volume: string;
    /**
     * Snapshot of the catalog name at the time of the workout.
     */
    readonly name: string;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutFinish = {
    perceived_effort?: number | null;
};

export type WorkoutFinishResult = {
    workout: WorkoutDetail;
    team_rewards: WorkoutTeamRewards;
    cardio_summary?: {
        [key: string]: unknown;
    } | null;
};

export type WorkoutList = {
    readonly id: number;
    workout_type: WorkoutTypeEnum;
    readonly started_at: string;
    readonly ended_at: string | null;
    readonly duration_minutes: number | null;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    readonly perceived_effort: number | null;
    validation_type: ValidationTypeEnum;
    readonly quality_score: number;
    readonly progress_score: number;
    status: Status31eEnum;
    readonly exercise_count: number;
    readonly total_volume: string;
    /**
     * Duration of the cardio session in minutes.
     */
    readonly cardio_duration_minutes: number | null;
    /**
     * Average pace in seconds per kilometer (lower is faster).
     */
    readonly cardio_pace_seconds_per_km: number | null;
    readonly cardio_pace_display: string;
    readonly created: string;
    readonly modified: string;
};

export type WorkoutProof = {
    photo: string;
    caption?: string;
};

export type WorkoutTeamRewards = {
    gains: Array<TeamPokemonGain>;
    empty_team: boolean;
};

/**
 * * `chest_triceps` - Chest & triceps
 * * `back_biceps` - Back & biceps
 * * `legs` - Legs
 * * `shoulders` - Shoulders
 * * `arms` - Arms
 * * `cardio` - Cardio
 * * `full_body` - Full body
 * * `mobility` - Mobility
 */
export type WorkoutTypeEnum = 'chest_triceps' | 'back_biceps' | 'legs' | 'shoulders' | 'arms' | 'cardio' | 'full_body' | 'mobility';

export type ExerciseWritable = {
    name: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
};

export type FriendRequestsResponseWritable = {
    incoming: Array<unknown>;
    outgoing: Array<unknown>;
};

export type GiftNotificationWritable = {
    [key: string]: unknown;
};

export type GiftSpeciesOptionWritable = {
    sort_order?: number;
};

export type LastWorkoutByTypeWritable = {
    [key: string]: unknown;
};

export type PaginatedExerciseListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedUserBriefListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedWorkoutListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PatchedExerciseWritable = {
    name?: string;
    description?: string;
    /**
     * Step-by-step guidance shown to the user.
     */
    instructions?: string;
    muscle_group?: MuscleGroupEnum;
    difficulty?: DifficultyEnum;
    /**
     * e.g. barbell, dumbbell, bodyweight
     */
    equipment?: string;
    /**
     * Demonstration image (max 5 MB, JPG/PNG/WebP).
     */
    image?: string | null;
    /**
     * Optional external video demonstrating the movement.
     */
    video_url?: string;
    /**
     * Inactive exercises are hidden from users but kept for history.
     */
    is_active?: boolean;
};

export type PatchedUserWritable = {
    email?: string;
    /**
     * Apelido único visível no app (3–24 caracteres, a-z, 0-9, _).
     */
    nickname?: string;
    /**
     * Slug do sprite de treinador (Pokémon Showdown).
     */
    trainer_sprite?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
};

export type PatchedWorkoutDetailWritable = {
    [key: string]: unknown;
};

export type PendingEncounterWritable = {
    workout_id: number;
    encounter_status: string;
    encounter_level: number | null;
    weekly_goal_reward: boolean;
};

export type PokemonSpeciesWritable = {
    pokedex_id: number;
    name: string;
    type_1: Type2Enum;
    type_2?: Type2Enum | BlankEnum;
    base_hp: number;
    base_attack: number;
    base_defense: number;
    base_sp_attack: number;
    base_sp_defense: number;
    base_speed: number;
    sprite_url?: string;
    official_artwork_url?: string;
    rarity?: RarityEnum;
};

export type RegisterWritable = {
    email: string;
    nickname: string;
    password: string;
    trainer_sprite?: string;
    invite_code?: string;
};

export type TimelineEventWritable = {
    type: string;
    at: string;
    workout?: TimelineWorkout | null;
    encounter?: TimelineEncounter | null;
    pokemon?: TimelinePokemon | null;
};

export type UserWritable = {
    email: string;
    /**
     * Apelido único visível no app (3–24 caracteres, a-z, 0-9, _).
     */
    nickname: string;
    /**
     * Slug do sprite de treinador (Pokémon Showdown).
     */
    trainer_sprite?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
};

export type UserPokemonDetailWritable = {
    nickname?: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
};

export type UserPokemonListWritable = {
    nickname?: string;
    level?: number;
    experience?: number;
    nature?: NatureEnum;
    shiny?: boolean;
    /**
     * Team position 1-6 when assigned to the active roster.
     */
    active_team_slot?: number | null;
    affection?: number;
    captured_at: string;
};

export type WorkoutCreateWritable = {
    workout_type?: WorkoutTypeEnum;
    started_at?: string;
    /**
     * Rate of perceived exertion from 1 to 10.
     */
    perceived_effort?: number | null;
    validation_type?: ValidationTypeEnum;
};

export type WorkoutDetailWritable = {
    [key: string]: unknown;
};

export type WorkoutExerciseWritable = {
    sets: number;
    reps: number;
    weight?: string;
    is_pr?: boolean;
};

export type WorkoutExerciseCreateWritable = {
    exercise: number;
    sets: number;
    reps: number;
    weight?: string;
    is_pr?: boolean;
};

export type WorkoutFinishResultWritable = {
    cardio_summary?: {
        [key: string]: unknown;
    } | null;
};

export type ExercisesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/exercises/';
};

export type ExercisesListResponses = {
    200: PaginatedExerciseListList;
};

export type ExercisesListResponse = ExercisesListResponses[keyof ExercisesListResponses];

export type ExercisesCreateData = {
    body: ExerciseWritable;
    path?: never;
    query?: never;
    url: '/api/exercises/';
};

export type ExercisesCreateResponses = {
    201: Exercise;
};

export type ExercisesCreateResponse = ExercisesCreateResponses[keyof ExercisesCreateResponses];

export type ExercisesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ExercisesDestroyResponse = ExercisesDestroyResponses[keyof ExercisesDestroyResponses];

export type ExercisesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesRetrieveResponses = {
    200: Exercise;
};

export type ExercisesRetrieveResponse = ExercisesRetrieveResponses[keyof ExercisesRetrieveResponses];

export type ExercisesPartialUpdateData = {
    body?: PatchedExerciseWritable;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesPartialUpdateResponses = {
    200: Exercise;
};

export type ExercisesPartialUpdateResponse = ExercisesPartialUpdateResponses[keyof ExercisesPartialUpdateResponses];

export type ExercisesUpdateData = {
    body: ExerciseWritable;
    path: {
        /**
         * A unique integer value identifying this exercise.
         */
        id: number;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesUpdateResponses = {
    200: Exercise;
};

export type ExercisesUpdateResponse = ExercisesUpdateResponses[keyof ExercisesUpdateResponses];

export type ExercisesImportCreateData = {
    body?: Array<{
        [key: string]: unknown;
    }> | {
        exercises?: Array<{
            [key: string]: unknown;
        }>;
        create_only?: boolean;
        dry_run?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/exercises/import/';
};

export type ExercisesImportCreateErrors = {
    400: {
        detail?: string;
    };
};

export type ExercisesImportCreateError = ExercisesImportCreateErrors[keyof ExercisesImportCreateErrors];

export type ExercisesImportCreateResponses = {
    200: {
        results?: Array<{
            name?: string;
            status?: string;
            reason?: string;
        }>;
        summary?: {
            created?: number;
            updated?: number;
            skipped?: number;
            failed?: number;
            total?: number;
        };
        dry_run?: boolean;
    };
};

export type ExercisesImportCreateResponse = ExercisesImportCreateResponses[keyof ExercisesImportCreateResponses];

export type FriendsAcceptCreateData = {
    body?: UserBrief;
    path: {
        /**
         * A unique integer value identifying this friendship.
         */
        id: number;
    };
    query?: never;
    url: '/api/friends/{id}/accept/';
};

export type FriendsAcceptCreateResponses = {
    200: UserBrief;
};

export type FriendsAcceptCreateResponse = FriendsAcceptCreateResponses[keyof FriendsAcceptCreateResponses];

export type FriendsBlockCreateData = {
    body?: UserBrief;
    path: {
        /**
         * A unique integer value identifying this friendship.
         */
        id: number;
    };
    query?: never;
    url: '/api/friends/{id}/block/';
};

export type FriendsBlockCreateResponses = {
    200: UserBrief;
};

export type FriendsBlockCreateResponse = FriendsBlockCreateResponses[keyof FriendsBlockCreateResponses];

export type FriendsDeclineCreateData = {
    body?: UserBrief;
    path: {
        /**
         * A unique integer value identifying this friendship.
         */
        id: number;
    };
    query?: never;
    url: '/api/friends/{id}/decline/';
};

export type FriendsDeclineCreateResponses = {
    200: UserBrief;
};

export type FriendsDeclineCreateResponse = FriendsDeclineCreateResponses[keyof FriendsDeclineCreateResponses];

export type FriendsRemoveDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this friendship.
         */
        id: number;
    };
    query?: never;
    url: '/api/friends/{id}/remove/';
};

export type FriendsRemoveDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type FriendsRemoveDestroyResponse = FriendsRemoveDestroyResponses[keyof FriendsRemoveDestroyResponses];

export type FriendsListListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/friends/list/';
};

export type FriendsListListResponses = {
    200: PaginatedUserBriefList;
};

export type FriendsListListResponse = FriendsListListResponses[keyof FriendsListListResponses];

export type FriendsRequestsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/friends/requests/';
};

export type FriendsRequestsRetrieveResponses = {
    200: FriendRequestsResponse;
};

export type FriendsRequestsRetrieveResponse = FriendsRequestsRetrieveResponses[keyof FriendsRequestsRetrieveResponses];

export type FriendsRequestsSendCreateData = {
    body?: FriendRequestCreate;
    path?: never;
    query?: never;
    url: '/api/friends/requests/send/';
};

export type FriendsRequestsSendCreateResponses = {
    200: Friendship;
};

export type FriendsRequestsSendCreateResponse = FriendsRequestsSendCreateResponses[keyof FriendsRequestsSendCreateResponses];

export type GiftsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gifts/';
};

export type GiftsListResponses = {
    200: Array<GiftNotification>;
};

export type GiftsListResponse = GiftsListResponses[keyof GiftsListResponses];

export type GiftsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gifts/{id}/';
};

export type GiftsRetrieveResponses = {
    200: GiftNotification;
};

export type GiftsRetrieveResponse = GiftsRetrieveResponses[keyof GiftsRetrieveResponses];

export type GiftsClaimCreateData = {
    body?: GiftClaim;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gifts/{id}/claim/';
};

export type GiftsClaimCreateResponses = {
    200: UserPokemonDetail;
};

export type GiftsClaimCreateResponse = GiftsClaimCreateResponses[keyof GiftsClaimCreateResponses];

export type GiftsPendingCountRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gifts/pending-count/';
};

export type GiftsPendingCountRetrieveResponses = {
    200: {
        count?: number;
    };
};

export type GiftsPendingCountRetrieveResponse = GiftsPendingCountRetrieveResponses[keyof GiftsPendingCountRetrieveResponses];

export type GiftsSendCreateData = {
    body: GiftSend;
    path?: never;
    query?: never;
    url: '/api/gifts/send/';
};

export type GiftsSendCreateResponses = {
    200: GiftSendResult;
};

export type GiftsSendCreateResponse = GiftsSendCreateResponses[keyof GiftsSendCreateResponses];

export type MyPokemonListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/my-pokemon/';
};

export type MyPokemonListResponses = {
    200: PaginatedUserPokemonListList;
};

export type MyPokemonListResponse = MyPokemonListResponses[keyof MyPokemonListResponses];

export type MyPokemonRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/my-pokemon/{id}/';
};

export type MyPokemonRetrieveResponses = {
    200: UserPokemonDetail;
};

export type MyPokemonRetrieveResponse = MyPokemonRetrieveResponses[keyof MyPokemonRetrieveResponses];

export type MyPokemonReleaseCreateData = {
    body: UserPokemonListWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/my-pokemon/{id}/release/';
};

export type MyPokemonReleaseCreateResponses = {
    /**
     * No response body
     */
    204: void;
};

export type MyPokemonReleaseCreateResponse = MyPokemonReleaseCreateResponses[keyof MyPokemonReleaseCreateResponses];

export type MyPokemonTeamSlotPartialUpdateData = {
    body?: PatchedUserPokemonTeamUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/my-pokemon/{id}/team-slot/';
};

export type MyPokemonTeamSlotPartialUpdateResponses = {
    200: UserPokemonTeamUpdate;
};

export type MyPokemonTeamSlotPartialUpdateResponse = MyPokemonTeamSlotPartialUpdateResponses[keyof MyPokemonTeamSlotPartialUpdateResponses];

export type MyPokemonCaptureCreateData = {
    body: UserPokemonCapture;
    path?: never;
    query?: never;
    url: '/api/my-pokemon/capture/';
};

export type MyPokemonCaptureCreateResponses = {
    200: UserPokemonDetail;
};

export type MyPokemonCaptureCreateResponse = MyPokemonCaptureCreateResponses[keyof MyPokemonCaptureCreateResponses];

export type MyPokemonRandomEncounterRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/my-pokemon/random-encounter/';
};

export type MyPokemonRandomEncounterRetrieveResponses = {
    200: PokemonSpecies;
};

export type MyPokemonRandomEncounterRetrieveResponse = MyPokemonRandomEncounterRetrieveResponses[keyof MyPokemonRandomEncounterRetrieveResponses];

export type MyPokemonTeamListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/my-pokemon/team/';
};

export type MyPokemonTeamListResponses = {
    200: PaginatedUserPokemonListList;
};

export type MyPokemonTeamListResponse = MyPokemonTeamListResponses[keyof MyPokemonTeamListResponses];

export type PokemonSpeciesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/pokemon-species/';
};

export type PokemonSpeciesListResponses = {
    200: PaginatedPokemonSpeciesList;
};

export type PokemonSpeciesListResponse = PokemonSpeciesListResponses[keyof PokemonSpeciesListResponses];

export type PokemonSpeciesRetrieveData = {
    body?: never;
    path: {
        pokedex_id: number;
    };
    query?: never;
    url: '/api/pokemon-species/{pokedex_id}/';
};

export type PokemonSpeciesRetrieveResponses = {
    200: PokemonSpecies;
};

export type PokemonSpeciesRetrieveResponse = PokemonSpeciesRetrieveResponses[keyof PokemonSpeciesRetrieveResponses];

export type RestRestCheckRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rest/rest-check/';
};

export type RestRestCheckRetrieveResponses = {
    200: Message;
};

export type RestRestCheckRetrieveResponse = RestRestCheckRetrieveResponses[keyof RestRestCheckRetrieveResponses];

export type TimelineListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * ISO datetime — retorna apenas eventos anteriores a este timestamp.
         */
        before?: string;
        /**
         * Máximo de eventos por página (padrão: 10, máx: 50).
         */
        limit?: number;
    };
    url: '/api/timeline/';
};

export type TimelineListResponses = {
    200: Array<TimelineFeed>;
};

export type TimelineListResponse = TimelineListResponses[keyof TimelineListResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/users/';
};

export type UsersListResponses = {
    200: PaginatedUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersCalendarRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/calendar/';
};

export type UsersCalendarRetrieveResponses = {
    200: User;
};

export type UsersCalendarRetrieveResponse = UsersCalendarRetrieveResponses[keyof UsersCalendarRetrieveResponses];

export type UsersFriendsListData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/users/{id}/friends/';
};

export type UsersFriendsListResponses = {
    200: PaginatedUserBriefList;
};

export type UsersFriendsListResponse = UsersFriendsListResponses[keyof UsersFriendsListResponses];

export type UsersPokemonRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/pokemon/';
};

export type UsersPokemonRetrieveResponses = {
    200: User;
};

export type UsersPokemonRetrieveResponse = UsersPokemonRetrieveResponses[keyof UsersPokemonRetrieveResponses];

export type UsersProfileRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/profile/';
};

export type UsersProfileRetrieveResponses = {
    200: {
        user?: {
            [key: string]: unknown;
        };
        is_self?: boolean;
        is_friend?: boolean;
        friend_count?: number;
        pokemon_count?: number;
        team_count?: number;
        current_streak?: number;
        joined_at?: string | null;
    };
};

export type UsersProfileRetrieveResponse = UsersProfileRetrieveResponses[keyof UsersProfileRetrieveResponses];

export type UsersTeamRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/team/';
};

export type UsersTeamRetrieveResponses = {
    200: User;
};

export type UsersTeamRetrieveResponse = UsersTeamRetrieveResponses[keyof UsersTeamRetrieveResponses];

export type UsersTimelineRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/timeline/';
};

export type UsersTimelineRetrieveResponses = {
    200: User;
};

export type UsersTimelineRetrieveResponse = UsersTimelineRetrieveResponses[keyof UsersTimelineRetrieveResponses];

export type UsersGiftRecipientsListData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Nickname or e-mail fragment (min. 1 character).
         */
        q: string;
    };
    url: '/api/users/gift-recipients/';
};

export type UsersGiftRecipientsListResponses = {
    200: PaginatedUserBriefList;
};

export type UsersGiftRecipientsListResponse = UsersGiftRecipientsListResponses[keyof UsersGiftRecipientsListResponses];

export type UsersInviteInfoRetrieveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Código de convite a ser validado.
         */
        code: string;
    };
    url: '/api/users/invite-info/';
};

export type UsersInviteInfoRetrieveResponses = {
    200: {
        id?: number;
        nickname?: string;
        display_name?: string;
        trainer_sprite?: string;
        trainer_sprite_url?: string;
    };
};

export type UsersInviteInfoRetrieveResponse = UsersInviteInfoRetrieveResponses[keyof UsersInviteInfoRetrieveResponses];

export type UsersLoginCreateData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/api/users/login/';
};

export type UsersLoginCreateResponses = {
    200: User;
};

export type UsersLoginCreateResponse = UsersLoginCreateResponses[keyof UsersLoginCreateResponses];

export type UsersLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/logout/';
};

export type UsersLogoutCreateResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersLogoutCreateResponse = UsersLogoutCreateResponses[keyof UsersLogoutCreateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: User;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];

export type UsersMePartialUpdateData = {
    body?: PatchedUserWritable;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMePartialUpdateResponses = {
    200: User;
};

export type UsersMePartialUpdateResponse = UsersMePartialUpdateResponses[keyof UsersMePartialUpdateResponses];

export type UsersRegisterCreateData = {
    body: RegisterWritable;
    path?: never;
    query?: never;
    url: '/api/users/register/';
};

export type UsersRegisterCreateResponses = {
    201: User;
};

export type UsersRegisterCreateResponse = UsersRegisterCreateResponses[keyof UsersRegisterCreateResponses];

export type UsersTrainerSpritesRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/trainer-sprites/';
};

export type UsersTrainerSpritesRetrieveResponses = {
    200: User;
};

export type UsersTrainerSpritesRetrieveResponse = UsersTrainerSpritesRetrieveResponses[keyof UsersTrainerSpritesRetrieveResponses];

export type WeeklyGoalListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/weekly-goal/';
};

export type WeeklyGoalListResponses = {
    200: Array<WeeklyGoalStatus>;
};

export type WeeklyGoalListResponse = WeeklyGoalListResponses[keyof WeeklyGoalListResponses];

export type WeeklyGoalCreateData = {
    body: SaveWeeklyGoal;
    path?: never;
    query?: never;
    url: '/api/weekly-goal/';
};

export type WeeklyGoalCreateResponses = {
    201: WeeklyGoalStatus;
};

export type WeeklyGoalCreateResponse = WeeklyGoalCreateResponses[keyof WeeklyGoalCreateResponses];

export type WorkoutsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/workouts/';
};

export type WorkoutsListResponses = {
    200: PaginatedWorkoutListList;
};

export type WorkoutsListResponse = WorkoutsListResponses[keyof WorkoutsListResponses];

export type WorkoutsCreateData = {
    body?: WorkoutCreateWritable;
    path?: never;
    query?: never;
    url: '/api/workouts/';
};

export type WorkoutsCreateResponses = {
    201: WorkoutCreate;
};

export type WorkoutsCreateResponse = WorkoutsCreateResponses[keyof WorkoutsCreateResponses];

export type WorkoutsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/';
};

export type WorkoutsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type WorkoutsDestroyResponse = WorkoutsDestroyResponses[keyof WorkoutsDestroyResponses];

export type WorkoutsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/';
};

export type WorkoutsRetrieveResponses = {
    200: WorkoutDetail;
};

export type WorkoutsRetrieveResponse = WorkoutsRetrieveResponses[keyof WorkoutsRetrieveResponses];

export type WorkoutsPartialUpdateData = {
    body?: PatchedWorkoutDetailWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/';
};

export type WorkoutsPartialUpdateResponses = {
    200: WorkoutDetail;
};

export type WorkoutsPartialUpdateResponse = WorkoutsPartialUpdateResponses[keyof WorkoutsPartialUpdateResponses];

export type WorkoutsCardioPreviewCreateData = {
    body: CardioPreview;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/cardio-preview/';
};

export type WorkoutsCardioPreviewCreateResponses = {
    200: CardioPreview;
};

export type WorkoutsCardioPreviewCreateResponse = WorkoutsCardioPreviewCreateResponses[keyof WorkoutsCardioPreviewCreateResponses];

export type WorkoutsCardioReferenceRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/cardio-reference/';
};

export type WorkoutsCardioReferenceRetrieveResponses = {
    200: CardioReference;
};

export type WorkoutsCardioReferenceRetrieveResponse = WorkoutsCardioReferenceRetrieveResponses[keyof WorkoutsCardioReferenceRetrieveResponses];

export type WorkoutsCardioSessionPartialUpdateData = {
    body?: PatchedCardioSession;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/cardio-session/';
};

export type WorkoutsCardioSessionPartialUpdateResponses = {
    200: WorkoutDetail;
};

export type WorkoutsCardioSessionPartialUpdateResponse = WorkoutsCardioSessionPartialUpdateResponses[keyof WorkoutsCardioSessionPartialUpdateResponses];

export type WorkoutsCardioSessionCreateData = {
    body: CardioSession;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/cardio-session/';
};

export type WorkoutsCardioSessionCreateResponses = {
    200: WorkoutDetail;
};

export type WorkoutsCardioSessionCreateResponse = WorkoutsCardioSessionCreateResponses[keyof WorkoutsCardioSessionCreateResponses];

export type WorkoutsDeclineEncounterCreateData = {
    body?: WorkoutDetailWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/decline-encounter/';
};

export type WorkoutsDeclineEncounterCreateResponses = {
    200: WorkoutDetail;
};

export type WorkoutsDeclineEncounterCreateResponse = WorkoutsDeclineEncounterCreateResponses[keyof WorkoutsDeclineEncounterCreateResponses];

export type WorkoutsExercisesCreateData = {
    body: WorkoutExerciseCreateWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/exercises/';
};

export type WorkoutsExercisesCreateResponses = {
    200: WorkoutExerciseCreate;
};

export type WorkoutsExercisesCreateResponse = WorkoutsExercisesCreateResponses[keyof WorkoutsExercisesCreateResponses];

export type WorkoutsExercisesDestroyData = {
    body?: never;
    path: {
        entry_id: string;
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/exercises/{entry_id}/';
};

export type WorkoutsExercisesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type WorkoutsExercisesDestroyResponse = WorkoutsExercisesDestroyResponses[keyof WorkoutsExercisesDestroyResponses];

export type WorkoutsExercisesPartialUpdateData = {
    body?: PatchedWorkoutExerciseUpdate;
    path: {
        entry_id: string;
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/exercises/{entry_id}/';
};

export type WorkoutsExercisesPartialUpdateResponses = {
    200: WorkoutExercise;
};

export type WorkoutsExercisesPartialUpdateResponse = WorkoutsExercisesPartialUpdateResponses[keyof WorkoutsExercisesPartialUpdateResponses];

export type WorkoutsExercisesBulkCreateData = {
    body: WorkoutExerciseBulkCreate;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/exercises/bulk/';
};

export type WorkoutsExercisesBulkCreateResponses = {
    200: WorkoutExerciseBulkCreate;
};

export type WorkoutsExercisesBulkCreateResponse = WorkoutsExercisesBulkCreateResponses[keyof WorkoutsExercisesBulkCreateResponses];

export type WorkoutsFinishCreateData = {
    body?: WorkoutFinish;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/finish/';
};

export type WorkoutsFinishCreateResponses = {
    200: WorkoutFinishResult;
};

export type WorkoutsFinishCreateResponse = WorkoutsFinishCreateResponses[keyof WorkoutsFinishCreateResponses];

export type WorkoutsFinishCardioCreateData = {
    body?: CardioWorkoutFinish;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/finish-cardio/';
};

export type WorkoutsFinishCardioCreateResponses = {
    200: WorkoutFinishResult;
};

export type WorkoutsFinishCardioCreateResponse = WorkoutsFinishCardioCreateResponses[keyof WorkoutsFinishCardioCreateResponses];

export type WorkoutsProofCreateData = {
    body: WorkoutProof;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workouts/{id}/proof/';
};

export type WorkoutsProofCreateResponses = {
    200: WorkoutDetail;
};

export type WorkoutsProofCreateResponse = WorkoutsProofCreateResponses[keyof WorkoutsProofCreateResponses];

export type WorkoutsActiveDraftRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workouts/active-draft/';
};

export type WorkoutsActiveDraftRetrieveResponses = {
    200: WorkoutDetail;
};

export type WorkoutsActiveDraftRetrieveResponse = WorkoutsActiveDraftRetrieveResponses[keyof WorkoutsActiveDraftRetrieveResponses];

export type WorkoutsCalendarRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workouts/calendar/';
};

export type WorkoutsCalendarRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type WorkoutsCalendarRetrieveResponse = WorkoutsCalendarRetrieveResponses[keyof WorkoutsCalendarRetrieveResponses];

export type WorkoutsLastByTypeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workouts/last-by-type/';
};

export type WorkoutsLastByTypeRetrieveResponses = {
    200: LastWorkoutByType;
};

export type WorkoutsLastByTypeRetrieveResponse = WorkoutsLastByTypeRetrieveResponses[keyof WorkoutsLastByTypeRetrieveResponses];

export type WorkoutsPendingEncounterRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workouts/pending-encounter/';
};

export type WorkoutsPendingEncounterRetrieveResponses = {
    200: PendingEncounter;
};

export type WorkoutsPendingEncounterRetrieveResponse = WorkoutsPendingEncounterRetrieveResponses[keyof WorkoutsPendingEncounterRetrieveResponses];
