# Generated by Django 5.2.14 on 2026-05-20 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ('-started_at',), 'verbose_name': 'workout', 'verbose_name_plural': 'workouts'},
        ),
        migrations.AddField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='perceived_effort',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rate of perceived exertion from 1 to 10.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='progress_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='workout',
            name='validation_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('health_app', 'Health app'), ('location', 'Location'), ('wearable_location', 'Wearable + location')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('chest_triceps', 'Chest & triceps'), ('back_biceps', 'Back & biceps'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('cardio', 'Cardio'), ('full_body', 'Full body'), ('mobility', 'Mobility')], default='full_body', max_length=32),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('volume', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('is_pr', models.BooleanField(default=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'workout exercise',
                'verbose_name_plural': 'workout exercises',
                'ordering': ('created',),
            },
        ),
    ]
