# Generated by Django 5.2.14 on 2026-05-20 20:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_options_workout_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(help_text='Snapshot of the catalog name at the time of the workout.', max_length=128),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='', help_text='Step-by-step guidance shown to the user.')),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full body'), ('mobility', 'Mobility')], default='full_body', max_length=32)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('equipment', models.CharField(blank=True, default='', help_text='e.g. barbell, dumbbell, bodyweight', max_length=128)),
                ('image', models.ImageField(blank=True, help_text='Demonstration image (max 5 MB, JPG/PNG/WebP).', null=True, upload_to=workouts.models.exercise_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('video_url', models.URLField(blank=True, default='', help_text='Optional external video demonstrating the movement.', max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive exercises are hidden from users but kept for history.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout_entries', to='workouts.exercise'),
        ),
    ]
