# Generated by Django 5.2.14 on 2026-05-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workout_weekly_goal_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='validation_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('photo', 'Photo proof'), ('health_app', 'Health app'), ('location', 'Location'), ('wearable_location', 'Wearable + location')], default='manual', max_length=32),
        ),
    ]
