# Generated by Django 5.2.14 on 2026-05-26 02:52

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_workout_cardio_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'workout comment',
                'verbose_name_plural': 'workout comments',
                'ordering': ('created',),
                'indexes': [models.Index(fields=['workout', 'created'], name='workouts_wo_workout_4f0745_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('emoji', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_reactions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'workout reaction',
                'verbose_name_plural': 'workout reactions',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['workout', 'emoji'], name='workouts_wo_workout_049393_idx')],
                'constraints': [models.UniqueConstraint(fields=('workout', 'user', 'emoji'), name='workout_reaction_unique')],
            },
        ),
    ]
