# Generated by Django 5.2.14 on 2026-05-26 03:05

from django.conf import settings
from django.db import migrations, models


def dedupe_reactions(apps, schema_editor):
    """Keep only the most recent reaction per (workout, user) pair."""
    WorkoutReaction = apps.get_model("workouts", "WorkoutReaction")
    seen: set[tuple[int, int]] = set()
    # Most recent first; later iterations are older duplicates to delete.
    ids_to_delete: list[int] = []
    for reaction in WorkoutReaction.objects.order_by("-created", "-id").values(
        "id", "workout_id", "user_id"
    ):
        key = (reaction["workout_id"], reaction["user_id"])
        if key in seen:
            ids_to_delete.append(reaction["id"])
        else:
            seen.add(key)
    if ids_to_delete:
        WorkoutReaction.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_workoutcomment_workoutreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutreaction',
            name='workout_reaction_unique',
        ),
        migrations.RunPython(dedupe_reactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='workoutreaction',
            constraint=models.UniqueConstraint(fields=('workout', 'user'), name='workout_reaction_unique_per_user'),
        ),
    ]
