# Generated by Django 5.2.14 on 2026-05-20 20:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters.', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms.', max_digits=5, null=True)),
                ('training_stage', models.CharField(choices=[('beginner', 'Beginner'), ('returning', 'Returning'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], default='beginner', max_length=32)),
                ('training_since', models.DateField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose weight'), ('build_muscle', 'Build muscle'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('general_fitness', 'General fitness'), ('maintenance', 'Maintenance')], default='general_fitness', max_length=32)),
                ('weekly_frequency', models.PositiveSmallIntegerField(default=3, help_text='Target workout sessions per week (1-7).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
