# Generated by Django 5.2.14 on 2026-05-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_invite_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interactions_last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que o usuário marcou as interações como vistas.', null=True),
        ),
    ]
